### ISSUE TITLE
Segmentation Fault when canceling a thread

### ISSUE THREAD

**Issue by PixelSpirit** [ocsigen/lwt#148]
Hy !

I am trying to use thread cancelation to program a timeout function.
Unfortunately, my program is interrupted by a segmentation fault just after the Lwt.cancel call.

Here is the code : 
```ocaml

open Lwt

let rec loop () =
  try_lwt
    Printf.printf "Still working ! \n%!";
    return () >> Lwt_main.yield () >> loop ()
  with Canceled ->
    Printf.printf "Someone canceled me ! \n%!";
    return ()

let timeout time thread =
  Lwt_unix.sleep i >>
  return (cancel thread)

let _ = 
  let l = loop () in
  Lwt_main.run (l <&> timeout 2.0 l);
  Printf.printf "Done ! \n%!"
```

The program crashes before printing ```Done !``` but if I use only 1 second as timeout, the program works well.

Is my code correct ?

**Comment by rneswold** [comment]
I'm not sure why it's seg faulting. However, it appears to be memory-related. Your loop eats up tons of memory because each iteration has to create a try-catch frame. I re-wrote your loop function like this:

```ocaml
let loop () =
  let rec inner_loop () =
    Printf.printf "Still working !\n";
    Lwt_main.yield () >> inner_loop ()
  in
  try_lwt
    inner_loop()
  with Cancelled ->
    Printf.printf "Someone canceled me !\n";
    return ()
```

This works. Even setting the timeout to 10 seconds works and the program runs in constant space. Nonetheless, I don't see why a seg fault should occur, so you may still have found a bug.

**Comment by PixelSpirit** [comment]
Thanks for your help and councils !

**Comment by gasche** [comment]
> Nonetheless, I don't see why a seg fault should occur when nesting try-catch frames, so you may still have found a bug.

Note that OCaml cannot guarantee that all instances of stack overflow will be properly handled with a `Stack_overflow` exception raised; some cases (typically if the stack blowup happens inside a C primitive instead of native OCaml code) may still lead to segfaults (and some architectures are harder to handle in this respect than others).

So what is said above is true, there may be a bug somewhere, but the segfault could also be explained by a simple stack overflow.

**Comment by rneswold** [comment]
> Note that OCaml cannot guarantee that all instances of stack overflow will be properly handled with a Stack_overflow exception raised; some cases (typically if the stack blowup happens inside a C primitive instead of native OCaml code) may still lead to segfaults (and some architectures are harder to handle in this respect than others).

Good point to remember. I feel, however, that this isn't a case of stack overflow. I was able to seg fault at both 2 seconds and 10 seconds. The 10 second run generated a 600MB core file. If it was a stack overflow error, I don't think it would have run for the full 10 seconds.

**Comment by edwintorok** [comment]
The crash reproduces with OCaml 4.01.0 `ulimit -s 1024` a 10s timeout and redirecting stdout to /dev/null. The stacktrace has 10970 entries: https://gist.github.com/anonymous/c89a1efa9193881e1d8d. With OCaml 4.02.3 it doesn't crash for me, it just hangs after 'Someone canceled me!' message.

**Comment by aantron** [comment]
I adjusted the program to consistently overflow the stack on my OS X system, with `ulimit -s 128` (at least 5 seconds), but always got stack overflow exceptions instead of segfaults, on both 4.01 and 4.02. This makes me think that this problem is most likely due to stack overflow only, and that receiving segfaults is system-specific, as mentioned by gasche. It is still possible that there is some system-specific code that is causing the segfaults without causing a stack overflow, but it doesn't seem very likely, and we need more information.

As already pointed out (thanks, everyone!), the solution for stack overflow is to rearrange the program.

I am closing this issue for now, but if you would like to debug it further, could you reply with what system you were running this on? Feel free to reopen it :)
