### ISSUE TITLE
Non sticky signals

### ISSUE THREAD

**Issue by antoine1fr** [ocsigen/lwt#165]
I have a worker thread that is alive the whole process' lifetime. It is idle when it has nothing to do, and is awaken by calls to `Lwt_condition.signal`. The problem is `signal` is not "sticky" so, currently, my worker can miss opportunities to wake up. Is there other mechanisms that I can use (for example like Windows' semaphores) ?

**Comment by aantron** [comment]
I don't know if you are still having this problem, but I would imagine that you have some kind of work queue in addition to the `Lwt_condition.t`. Your worker should check this queue each time it finishes a task, and only put itself to sleep on the condition if it finds the queue empty. Your work producers add things to the queue, always signaling the condition afterwards. Can you be more specific about how your worker misses opportunities to wake up?

**Comment by antoine1fr** [comment]
I effectively have a work queue and my worker thread works just as you described.

If I remember correctly, the problem arose when a signal was sent just before the worker went to sleep. The worker should immediately wake up and take the new job but, in practice, the worker didn't wake up.

**Comment by aantron** [comment]
I think in this case, as long as one of these two holds, the worker still shouldn't be able to miss the signal. Lwt runs as many "non-blocking" binds in a row without "descheduling" a thread as it can. So:

1. Your worker thread does not perform any I/O or other blocking operation, or do a `Lwt.wakeup`, `Lwt.yield`, or similar operation that switches threads, between the time it decides the queue is empty, and the time it sleeps on the condition. It is guaranteed not to be interrupted by any other thread during this interval.
2. Your worker thread does perform some of the operations these two points, but you take an `Lwt_mutex`, and protect both the `Lwt_condition.wait` (using the `~mutex` parameter) and `Lwt_condition.signal` with that mutex. Now, it is not possible to signal the condition during the interval.

Then the `signal` should be safe. Is it possible that your worker was getting descheduled, but the queue and condition were not protected by a mutex on both the producer and consumer sides?

Otherwise, there may be a bug in `Lwt_condition`. I just took a quick look, but I don't see any obvious problem yet.

**Comment by antoine1fr** [comment]
Thank you for your explanations! I will look into that as soon as I have the time. :)

**Comment by aantron** [comment]
I am closing this issue for now, but feel free to reopen if you have more info/find a bug lurking in `Lwt_condition` or elsewhere :)
