### ISSUE TITLE
`disable-libev` still tries to find `libev`

### ISSUE THREAD

**Issue by smondet** [ocsigen/lwt#271]
Seems to be called with ` --disable-libev`:

```
#=== ERROR while installing lwt.2.5.2 =========================================#
# opam-version 1.2.2
# os           linux
# command      ./configure --prefix /home/opam/.opam/4.02.3 --disable-libev --enable-camlp4 --enable-react --disable-ssl --enable-unix --enable-preemptive --disable-glib --enable-ppx
# path         /home/opam/.opam/4.02.3/build/lwt.2.5.2
# compiler     4.02.3
# exit-code    1
# env-file     /home/opam/.opam/4.02.3/build/lwt.2.5.2/lwt-28505-8b8a2d.env
# stdout-file  /home/opam/.opam/4.02.3/build/lwt.2.5.2/lwt-28505-8b8a2d.out
# stderr-file  /home/opam/.opam/4.02.3/build/lwt.2.5.2/lwt-28505-8b8a2d.err
### stdout ###
# [...]
# Please install them and retry. If they are installed in a non-standard location
# or need special flags, set the environment variables <LIB>_CFLAGS and <LIB>_LIBS
# accordingly and retry.
# 
# For example, if libev is installed in /opt/local, you can type:
# 
# export LIBEV_CFLAGS=-I/opt/local/include
# export LIBEV_LIBS=-L/opt/local/lib
# 
# To compile without libev support, use ./configure --disable-libev ...
```

**Comment by aantron** [comment]
This may not be caused by libev/`--disable-libev`. Can you please show the output line before the "Please install them and retry..." (show the `.out` log file or run `opam install --verbose`)? That is the line that lists the actual missing libraries. The rest of the stuff about libev is a fixed string output no matter what is actually missing.

This error message is confusing and should be changed. It's especially unfortunate that OPAM trims exactly the relevant line.

I tried to reproduce in Travis to see if this is likely a libev problem, but the build seems to work:

- libev is not (apparently) installed: [[1]](https://travis-ci.org/ocsigen/lwt/builds/161975596#L201) [[2]](https://travis-ci.org/ocsigen/lwt/builds/161975596#L1370),
- the flag is [passed](https://travis-ci.org/ocsigen/lwt/builds/161975596#L349),
- the build succeeds.

**Comment by smondet** [comment]
sorry @aantron I lost the docker container where this happened.

with a fresh docker run *and* inside a fresh linux VM, it now works, so maybe it's not Lwt's fault but just my linux box going nuts.

Feel free to close, I'll keep an eye if it happens again.

**Comment by aantron** [comment]
Alright, thanks for checking.

I'll leave this open for now, as an issue to at least fix that error message.
