### ISSUE TITLE
unable to set Lwt socket non blocking on my system:

### ISSUE THREAD

**Issue by cedlemo** [ocsigen/lwt#273]
Hi I have this code that blocks : 

```ocaml
open Lwt
open Unix

(* ocamlfind ocamlc -o lwt_socket_client -package lwt,lwt.unix,unix  -linkpkg -g lwt_socket_client.ml *)
let host = Unix.inet_addr_loopback 
let port = 6600

let create_socket () =
  let sock = Lwt_unix.socket PF_INET SOCK_STREAM 0 in
  Lwt_unix.set_blocking sock false;
  sock

let s_read sock maxlen =
  let str = Bytes.create maxlen in
  let rec _read sock acc =
    Lwt.ignore_result(Lwt_io.write_line Lwt_io.stdout "_read");
    Lwt_unix.read sock str 0 maxlen >>= fun recvlen ->
    Lwt.ignore_result(Lwt_io.write_line Lwt_io.stdout (string_of_int recvlen));
    if recvlen = 0 then Lwt.return (acc)
    else _read sock (acc ^ (String.sub str 0 recvlen))
  in _read sock ""

let socket_read sock =
  Lwt.ignore_result(Lwt_unix.connect sock @@ ADDR_INET(host, port));
  s_read sock 1024 >>= fun answer ->
  Lwt_io.write_line Lwt_io.stdout answer

let () =
  let sock = create_socket () in
    Lwt_main.run (socket_read sock)
```

When I run in a terminal for a test : 

```
echo "totoche" | netcat -l 127.0.0.1 -p 6600
```

my little client block while I have configured the socket as non blocking:

```
./lwt_socket_client
_read
8
_read
```

I have created a question in stackoverflow (http://stackoverflow.com/questions/39675231/ocaml-lwt-and-non-blocking-socket) and it seems that someone was able to run this code with the following output on OS X :

```
> ./lwt_socket_client 
_read
8
_read
0
totoche
```

Without focusing on the utility of this code , is it normal that the `set_block fd false` is not working on my system (ArchLinux x86_64)?

**Comment by aantron** [comment]
There are several things going on here.

Despite the docs ("`read fd buf ofs len` has the same semantic as `Unix.read`, but is cooperative"), looking at the code, `Lwt_unix.read` automatically schedules retrying for `Unix.read` to complete in case no data is available, even if the underlying socket is non-blocking. So, on an Lwt level, the "socket" is always "blocking." I'm not sure if that's how it *should* be, but that's how it is now. Opinions welcome.

Next, your issue seems to treat `0` as equivalent to "no data," but no data is signaled by failing with `EAGAIN` or `EWOULDBLOCK` (which Lwt swallows and retries). Succeeding with 0 indicates end of file. I suspect that the output on OS X is due to the connection being closed by the server, i.e. the difference is due to a race condition or a difference in the `netcat` implementations.

**Comment by aantron** [comment]
You may be able to use `Unix.read (Lwt_unix.unix_file_descr sock) str 0 maxlen` to get the effect you want – wrap this in a handler for `Unix.Unix_error (Unix.EAGAIN | Unix.EWOULDBLOCK)`.

**Comment by cedlemo** [comment]
Thanks  a lot this was really helpfull (fell free to answer on SO, I will validate your answer).

**Comment by aantron** [comment]
Done on SO. I'm going to reopen this issue for now as a reminder to update the docs of both `Lwt_unix.read` and `Lwt_unix.set_blocking`, because they are misleading. Should probably also edit docs of `Lwt.ignore_result`. Thanks for reporting.
