### ISSUE TITLE
Lwt_unix.file_exists can raise `Unix.ENOTDIR`

### ISSUE THREAD

**Issue by samoht** [ocsigen/lwt#316]
Test case:

``` 
$ touch foo
$ ocaml
# require "lwt.unix";;
# Lwt_main.run (Lwt_unix.file_exists "foo/bar");;
Exception: Unix.Unix_error (Unix.ENOTDIR, "stat", "_log/toto").
# Sys.file_exists "foo/bar";;
- : bool = false
```

**Comment by mfp** [comment]
I went ahead and committed this even though it breaks "bug for bug" compatibility because existent code able to cope with spurious exceptions raised by `file_exists` must handle the case where it returns `false` anyway, and it seems very unlikely anybody would rely on these exceptions being raised (and handle them differently to the `false` case).
