### ISSUE TITLE
Add ?cloexec parameter to Lwt_unix functions that create file descriptors

### ISSUE THREAD

**Issue by mfp** [ocsigen/lwt#327]
OCaml 4.05 adds an optional `cloexec` parameter to several Unix functions, allowing the close-on-exec flag to be set as the operation is performed atomically on some platforms (limited to Linux atm.) -- otherwise there's a race condition when there are multiple (system) threads.

These functions would be affected: `Lwt_unix.dup`, `dup2`, `pipe`, `socket`, `socketpair`, `accept`.
Other functions that build on them and could also take `?cloexec`: `accept_n`, `pipe_in`, `pipe_out`.

**Comment by aantron** [comment]
I'm closing this issue for now, because:

- The issue with multiple threads is probably less likely in typical Lwt programs, than even in programs using only `Unix`.
- We haven't had any reports of a problem due to this.

We can reopen and fix later, if necessary.

Here's a link to text about the issue in module `Unix`: https://caml.inria.fr/pub/docs/manual-ocaml/libref/Unix.html#VALset_close_on_exec.
