### ISSUE TITLE
Move the PPX to a separate package (?)

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#338]
I'm not sure if it ought to also be ported to `ocaml-migrate-parsetree`. If so, then port it.

IMO the PPX syntax is much easier to teach than `>|= fun blah ->` everywhere, so I've been writing new docs in terms of it. However, we can just tell newcomers to do `opam install lwt lwt_ppx`. Projects that avoid the PPX for whatever reason can do `opam install lwt` and not have to wait for ports of `ppx_tools`/`ocaml-migrate-parsetree` to new versions of OCaml.

On the other hand, maybe we should just make an effort to make sure that those ports don't take a long time. Also, `ppx_tools` and `ocaml-migrate-parsetree` are such basic packages, that installing several OPAM packages is likely to pull them in whether they are dependencies of the base `lwt` or not.

Please let me know any thoughts on this.

Prompted by @avsm in https://github.com/ocaml/opam-repository/pull/8929#issuecomment-293622509.

EDIT: and there is a previous similar (but not identical) request in #266.

**Comment by Drup** [comment]
Splitting the ppx inside its own package and porting it to ocaml-migrate-parsetree are two completely independent tasks (and would not be done for the same reasons).

I have no opinion on the first. Doing the second while we have oasis needs far too many hacks, and it would be easier to just port lwt to something else.

**Comment by avsm** [comment]
Agree with @drup -- just moving the package out would be a good first start, since a significant number of packages do not use the ppx extension at all, and it's a pity when the core Lwt package fails to build when ppx is not available.

My request is specifically motivated by the desire to do more CI testing with development branches of OCaml, and this is the most common reason why ppx is unavailable (due to an AST change).  Lwt blocks a very large number of packages from building, but a significant percentage of those do not have a hard ppx dependency.
