### ISSUE TITLE
Segfault when reading wrong type from channel

### ISSUE THREAD

**Issue by alinpopa** [ocsigen/lwt#345]
```
OS: Macos 10.12.4
Ocaml: 4.04.1 (installed from homebrew)
Lwt: 2.7.1
```

I'm trying to do the following (this is from an utop session):
```
> #require "lwt";;
> open Lwt.Infix;;
> let (ic, oc) = Lwt_io.pipe ();;
> let read_data ic =
  Lwt.async (fun () ->
    let rec loop () = Lwt_io.read_value ic >>= fun v ->
      print_endline ("Data: " ^ v);
      loop ()
    in
    loop ());;
> read_data ic;;
> Lwt_io.write_value oc "msg1";; (* This works fine, i.e. the message is being consumed *)
> Lwt_io.write_value oc "msg2";; (* This works fine, i.e. the message is being consumed *)
> Lwt_io.write_value oc 5;;
zsh: segmentation fault  utop
```
Not sure what I'm missing here; also, apologies if this was already opened, but I wasn't able to find it.
Thanks.

**Comment by hcarty** [comment]
`Lwt_io.write_value` and​ `Lwt_io.read_value` are unsafe - there is no hidden type checking or coercion happening in the background.

The first two writes work because the values written are strings and that's what's expected by the reading code. The third segfaults because an integer is written and then interpreted as a string on the read side.

**Comment by alinpopa** [comment]
> Lwt_io.write_value and​ Lwt_io.read_value are unsafe

Ah, ok; this I didn't know;
I figured that everything is alright for the first two because they're strings, and string was expected, but honestly for an int, I'd expect at least an exception, and not a total crash.
Thanks.

**Comment by hcarty** [comment]
I think the reason for a lack of exception is that there is no runtime type information, so no way to check the validity of the bytes provided. It's assumed (though maybe not emphasized clearly?) that some of kind wrapper would be used around these functions, providing appropriate type constraints manually to ensure type safety.

**Comment by aantron** [comment]
This is the behavior of the standard [`Marshal`](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Marshal.html) module from the standard library, questionable as it may be, and it's also the behavior of [`Pervasives.input_value`](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Pervasives.html#VALinput_value). I think the idea is that if you need to add tags to the marshaled data to be able to unmarshal it correctly, you will add those tags to the output stream yourself (and read appropriately). Otherwise, type constraints in your program should be preventing incorrect behavior.

What we should do is leave this issue open, to remind ourselves to document this dangerous behavior, and link to `Marshal` and `Pervasives.input_value`/`Pervasives.output_value`, so people know what to expect.

**Comment by mfp** [comment]
On Sat, Apr 29, 2017 at 11:25:00AM -0700, Alin Popa wrote:
> > Lwt_io.write_value and​ Lwt_io.read_value are unsafe
> 
> Ah, ok; this I didn't know;
> I figured that everything is alright for the first two because they're
> strings, and string was expected, but honestly for an int, I'd expect at
> least an exception, and not a total crash.

Lwt_io.write_value/read_value simply use Marshal under the hood, so the
following notice from its manpage/documentation applies:

       Warning:  marshaling  is  currently  not type-safe. The type of
       marshaled data is not transmitted along the value of the  data,
       making it impossible to check that the data read back possesses
       the type expected by the context.  In  particular,  the  result
       type  of the Marshal.from_* functions is given as 'a , but this
       is misleading: the returned OCaml value does not  possess  type
       'a  for all 'a ; it has one, unique type which cannot be deter‐
       mined at compile-type.  The programmer should  explicitly  give
       the  expected  type  of the returned value, using the following
       syntax:

       - (Marshal.from_channel chan : type) .  Anything can happen  at
       run-time if the object in the file does not belong to the given
       type.

There's an additional gotcha relative to exceptions and extensible variant
types:

       Values of extensible variant types,  for  example  exceptions  (of
       extensible  type exn ), returned by the unmarhsaller should not be
       pattern-matched over through match ... with  or  try  ...  with  ,
       because  unmarshalling  does not preserve the information required
       for matching their constructors. Structural equalities with  other
       extensible  variant  values does not work either.  Most other uses
       such as Printexc.to_string, will still work as expected.

-- 
Mauricio Fernández

**Comment by aantron** [comment]
> at compile-type

I guess I'll open a PR to ocaml/ocaml to fix this typo..

**Comment by alinpopa** [comment]
Thanks guys; it makes sense right now; it's my bad as I didn't get to read that documentation bit.

**Comment by aantron** [comment]
Thanks for reporting!
