### ISSUE TITLE
The paths of Lwt's installed cmi files

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#364]
@diml in https://github.com/ocaml/opam-repository/pull/9228#issuecomment-302756447:

> qcow-tool fails to build in one the datakit build. I check, it's because mirage-block-unix uses Lwt_unix but lwt.unix is missing from the jbuild. It's not detected at build time since the cmi files for lwt.unix are installed in the same directory as the cmi files for lwt.
>
> /cc @aantron, it'd be better to install the cmi for the various sub-libraries in sub-directories, to avoid problems like these. jbuilder installs the files for a library with findlib name a.b.c in <lib-dir>/a/b/c.

~~This seems like a problem with jbuilder being incompatible with non-jbuilder installs; on the other hand, maybe we can just~~ move these `.cmi` files in the next release, ~~and avoid friction~~.

cc @djs55 @rgrinberg 

EDIT: instructions for testing are [below](https://github.com/ocsigen/lwt/issues/364#issuecomment-303116926).

**Comment by Drup** [comment]
The recent oasis feature called "FindlibDirectory" should allow to do that quite easily.

**Comment by aantron** [comment]
So I guess this is a matter of

1. Adding `FindlibDirectory` to each Findlib library package in `_oasis` that has a `FindlibParent` ([example](https://github.com/ocsigen/lwt/blob/cf5580b6362a05087227f6b889a3a6e6094baee8/_oasis#L132-L136)).
2. Finding out what version of [OASIS](https://github.com/ocaml/oasis) implements `FindlibParent`, either by reading its [changelog](https://github.com/ocaml/oasis/blob/master/CHANGES.txt), or somehow through blame in that repo.
3. Making sure Lwt's [`opam` file](https://github.com/ocsigen/lwt/blob/cf5580b6362a05087227f6b889a3a6e6094baee8/opam/opam#L43) requires at least that version of OASIS.

**Comment by diml** [comment]
FTR, jbuilder is compatible with non-jbuilder installs. It simply reads META files like ocamlfind. The issue I was talking about in the PR is the following:

1. create a file referencing Lwt_unix
2. compile it with `ocamlfind ocamlc -package lwt -c ...`
3. link an exectuable with `ocamlfind ocamlc -package lwt -o ...`

Only step (3) will fail. Which is unfortunate because if the user forgets to state a dependency on lwt.unix, then they won't get an error until much later when someone tries to link an executable with their libraries. The right way to deal with include paths is to have one library per directory, and that's what jbuilder enforces for libraries it installs itself.

**Comment by aantron** [comment]
Thanks for clarifying, @diml.

So, I guess to work on this, one would:

1. Pin Lwt `master` with `opam source --dev-repo --pin lwt`.
2. Follow the instructions from @diml's [post above](https://github.com/ocsigen/lwt/issues/364#issuecomment-303030400) to reproduce the issue.
3. Make a git branch and make the change to `_oasis` [described above](https://github.com/ocsigen/lwt/issues/364#issuecomment-302889878).
4. `opam reinstall lwt` (or `opam upgrade lwt`?) to install a version of Lwt from your branch, with the `_oasis` change included.
5. Follow the same steps as in (2) to reproduce, but make sure they don't trigger an error this time.
6. PR the branch to the Lwt repo.

**Comment by aantron** [comment]
This was resolved by #374.
