### ISSUE TITLE
Use cstruct?

### ISSUE THREAD

**Issue by raphael-proust** [ocsigen/lwt#396]
Currently, providing new system calls involve several files with many macros.

Is this the kind of thing that cstruct could make simpler? And if so
How many dependencies cstruct has? Which ones?
Is it worth rewriting the unix bindings with a cstruct version?

I'll investigate some of that. If someone already have answers to those questions, please comment below.

**Comment by aantron** [comment]
The status of this is:

- We'd like to make the C code more maintainable. It's really rough right now. Using `Lwt_preemptive` (perhaps improved) with cstruct is definitely a good way to do that.
- I believe this is more or less how Async does most (or all?) of its blocking system calls, e.g. [this link](https://github.com/janestreet/async_unix/blob/master/src/unix_syscalls.ml#L338) is from the `getcwd` issue.
- I believe the reason for why there is a whole bunch of C code in Lwt, is because when not compiling with `-threads`, `Thread`, `Mutex`, etc. are not available. So, a threading module got implemented in C. I haven't looked in the configuration to know deeply enough, but: is there a platform on which Lwt could be configured to compile all that threaded C code, that doesn't have OCaml threads? If so, is that platform important? I didn't look, but does the C code compile to blocking code if threads are not available in C?
- There is also the minor issue of the global interpreter lock, which would be taken by calling back into OCaml right before doing a system call. I doubt this is important, however. It also shouldn't be an issue once the multicore runtime is available.
- The biggest thing constraining this right now is the potential port to libuv (#328), which would replace Lwt's C code by uwt/libuv, rather than by `Lwt_preemptive`+cstruct. I think this is a more promising direction, as we could also provide an isomorphic Node.js binding (#270) for use with js_of_ocaml and BuckleScript, and expect to get (almost?) the same semantics (since Node.js is calling libuv internally). Together with a port of the core to ES6 promises, Lwt could provide a common I/O library for porting code and skill sets beween Node and native, and the core between Node, native, and front-end. It would also unite the various ecosystems to some degree. This could be a major win for convincing people to adopt OCaml and Reason :)
- Interestingly, libuv [doesn't have](https://github.com/ocsigen/lwt/issues/342#issuecomment-295844277) a non-blocking wrapper around `getcwd`, but [uwt does](https://github.com/fdopen/uwt/blob/1d607f8e7da9836ab98bcd9555ec4cbcd92047f7/src/uwt.ml#L1476), so we may still want to use cstruct for a portion of the API, even if we go down the uwt/libuv path.

**Comment by aantron** [comment]
The other effect of using libuv is that Windows will get first-class support.

**Comment by avsm** [comment]
I agree with @aantron that the port to libuv would be more fruitful than using Cstruct, in the short term.  We've had good results with using libuwt in [vpnkit](https://github.com/moby/vpnkit/blob/master/src/hostnet/host_uwt.ml)

**Comment by aantron** [comment]
Closing this as accepted, because we definitely want to use cstruct/ctypes, and it's on our minds for any major future Lwt work.
