### ISSUE TITLE
Lwt_array with map(i)_p, map(i)_s, iter(i)_p, iter(i)_s

### ISSUE THREAD

**Issue by toolslive** [ocsigen/lwt#414]
Currently, if you need to map_p over an array, you need to convert it to a list, and remap afterwards, which is inefficient.
If there's interest, I'm willing to do the grunt work.

**Comment by aantron** [comment]
It sounds useful. Maybe we should discuss this for a few days: should there be a separate data structures library over Lwt, or we just extend Lwt with any needed modules?

**Comment by toolslive** [comment]
Now, `iter(i)_s` and `map(i)_s` are very simple. `map(i)_p` can be built on the outside, using something like a [count down latch](https://github.com/openvstorage/alba/blob/75344425658e33e3fb7a6b4874e8f7d1e66320b7/ocaml/src/tools/lwt_extra2.ml#L43). There might be simpler approaches too.

But, I was wondering if it's worth it to change `Lwt.join` and make it a bit more generic so it is possible to join over other container types as well. This way everybody can map_p over whatever floats their boat.

**Comment by aantron** [comment]
If you can design such a `join` (I guess it would take some higher-order `iter` function?), it might be nice to have in a gist or comment. It might take some discussion to decide on what to do with it, but sounds interesting. We would probably be adding a new `join` rather than modifying the existing one.

Also, note there is #325 about binary `join` (and `choose`) that preserves the results of both computation. Not directly related, but another proposal on `join`.

**Comment by aantron** [comment]
I think I, and several other people, would welcome generalizing traversal over data structures, but I don't have time to do a good job on designing this in the immediate term :(

**Comment by aantron** [comment]
@toolslive, I think the status of this issue is:

- We had a discussion about this some months ago, and decided to put it off.
- In the meantime, I also tried writing a "generic" `join` and `choose` with modular implicits, and had some fairly promising results.

I suggest to close this issue for now, though, since I don't think it will be worked on soon, or can necessarily be solved in a good way in modern OCaml.

What do you think?

**Comment by hcarty** [comment]
[gen](https://github.com/c-cube/gen/) is generally a good option too.  [GenM.Make(Lwt)](http://cedeela.fr/~simon/software/gen/GenM.html) would provide some of the desired functionality.  @c-cube may be willing to take contributions to add potentially missing functions.

I know it has some downsides, but Lwt\_stream is a often a reasonable choice for concurrent array iteration too.

**Comment by toolslive** [comment]
I looked at making `join` and `choose` more generic using combinators for iteration, and was able to peel off one layer of the onion. The use of lists is however deeply ingrained in the state management of promises too.... so it's just not enough. As far as I'm concerned, you can close this one ;)

**Comment by aantron** [comment]
Okay. This seems like a "future work" issue :) Thanks for getting back.
