### ISSUE TITLE
A glitch of Lwt.cancel

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#415]
Described by @camlspotter at https://bitbucket.org/camlspotter/lwt_cancel_glitch:

> In lwt.2.7.0, it seems that `Lwt.cancel` cannot cancel the thread itself in which `Lwt.cancel` is called.  The call of `Lwt.cancel` has no effect. For example, the following code cannot cancel the thread execution:
> 
> ```ocaml
> let self = ref None
>     
> let from_some = function
>   | Some x -> x
>   | None -> assert false
>     
> let s =
>   pause () >>= fun () ->
>   cancel (from_some !self);
>   prerr_endline "cancel called";
>   pause () >>= fun () ->
>   prerr_endline "direct cancel cannot cancel itself";
>   return ()
>     
> let () =
>   self := Some s;
>   prerr_endline "set";
>   Lwt_main.run @@ s
> ```
> 
> In order to kill the current thread, it seems that we need to call `Lwt.cancel` from another thread.  For example, the following code wraps the call of `Lwt.cancel` by `Lwt.async (fun () -> Lwt.pause () >>= fun () -> ...)`:
> 
> ```ocaml
> let self = ref None
>     
> let from_some = function
>   | Some x -> x
>   | None -> assert false
>     
> let s =
>   pause () >>= fun () ->
>   async (fun () ->
>     pause () >>= fun () ->
>     cancel (from_some !self);
>     prerr_endline "cancel called";
>     return ());
>   pause () >>= fun () ->
>   prerr_endline "not dead";
>   return ()
>     
> let () =
>   self := Some s;
>   prerr_endline "set";
>   Lwt_main.run @@ s
> ```

I'm not sure if this qualifies as a bug or a misunderstanding (due to unclear terminology and cancel semantics in Lwt).

**Comment by raphael-proust** [comment]
AFAICT, this is the same problem as with #283 : by the time `cancel` is called, the “deepest” promise (the first `pause`) is resolved, and so the cancellation has no effect.

This case is harder though, because the deepest non-resolved promise is the one that is calling for the cancellation and thus the one that is “currently executing”. The difficult part being that we (at least I) would expect this code to behave like:

```
  pause () >>= fun () ->
  cancel (from_some !self);
  prerr_endline "cancel called";
  fail Canceled >>= fun () ->
  prerr_endline "direct cancel cannot cancel itself";
  return ()
```

This means the instruction `prerr_endline "cancel called"` should happen before the cancellation is observed by other threads.

**Comment by aantron** [comment]
Closing with the explanation in https://github.com/ocsigen/lwt/issues/283#issuecomment-518014539.
