### ISSUE TITLE
Lwt_unix.timeout may return early

### ISSUE THREAD

**Issue by stijn-devriendt** [ocsigen/lwt#427]
We are observing that Lwt_unix.timeout can sometimes return early.

The case that we were able to debug a bit more closer was doing a very lengthy writeout to the console (multiple megabytes), from an Lwt task. The next operation with an Lwt_unix.timeout raised Lwt_unix.Timeout early. Suppressing the writeout gave normal behavior.

Digging a bit deeper, I believe the following behavior in libev is causing this:
>The special problem of time updates
>
>Establishing the current time is a costly operation (it usually takes at least two system calls): EV
>therefore updates its idea of the current time only before and after "ev_run" collects new events, which 
>causes a growing difference between "ev_now ()" and "ev_time ()" when handling lots of events in one 
>iteration.
>
>The relative timeouts are calculated relative to the "ev_now ()" time. This is usually the right thing as this 
>timestamp refers to the time of the event triggering whatever timeout you are modifying/starting. If 
>you suspect event processing to be delayed and you need to base the timeout on the current time, use 
>something like this to adjust for this:
>
>ev_timer_set (&timer, after + ev_now () - ev_time (), 0.);
>
>If the event loop is suspended for a long time, you can also force an update of the time returned by 
>"ev_now ()" by calling "ev_now_update ()". 

See also [man ev](https://linux.die.net/man/3/ev)

When an Lwt.t already has a value or exception, a bind will simply continue execution. This may, in the absence of I/O, cause lengthy periods of not going back into the libev event loop, causing the ev_now time-base to become stale. The next Lwt_engine.on_timer call will then have a relative timeout based on the old time-base, making the timeout shorter than expected.

Reproducer usable in the Lwt testsuite:
```
  test "libev"
    (fun () ->
       let start = Unix.gettimeofday () in
       let stop = ref start in
       let t1 = catch (fun () ->
          let () = Unix.sleep 3 in
          Lwt_unix.timeout 1.;
         )
           (function
            | Lwt_unix.Timeout ->
              let () = stop := Unix.gettimeofday () in
              return ()
            | exn -> Lwt.fail exn
           )
       in
       bind t1 (fun () ->
           let () = Printf.printf "start = %f, stop= %f, delta=%f\n"
               start
               (!stop)
               ((!stop) -. start)
           in
           return ((!stop) -. start >= 4.))
    );
```
This traces:
start = 1498665441.874718, stop= 1498665444.876054, delta=3.001336

A potential fix could be this:
```
diff --git a/src/unix/lwt_libev_stubs.c b/src/unix/lwt_libev_stubs.c
index 66ccb4a..57ef001 100644
--- a/src/unix/lwt_libev_stubs.c
+++ b/src/unix/lwt_libev_stubs.c
@@ -191,6 +191,7 @@ CAMLprim value lwt_libev_timer_init(value loop, value delay, value repeat, value
 {
   CAMLparam4(loop, delay, repeat, callback);
   CAMLlocal1(result);
+  ev_now_update(Ev_loop_val(loop));
   /* Create and initialise the watcher */
   struct ev_timer* watcher = lwt_unix_new(struct ev_timer);
   if (Bool_val(repeat))
```
(Beware this is against a 2.5.0 version of Lwt).

**Comment by aantron** [comment]
Thanks for adding the reproducer and potential fix (and the report, of course). I'll take a harder look (at some point, hopefully relatively soon) at the performance implications of this. My guess is that the rate of calling `ev_now_update` will be proportional to the degree that the program is I/O-bound, and so it probably won't be an issue.

**Comment by stijn-devriendt** [comment]
As far as I know, the on_timer is only called for Lwt.sleep (and Lwt_unix.timeout) so the performance impact should be limited.
Given that the issue is with "uncooperative" tasks, I also considered whether Lwt.yield would be a good candidate, but I'm not sure it is. Uncooperativeness could be a bug (e.g. a larger than expected debug trace) or people could be happy with performance even if large unpreemptible CPU-bound tasks are used. Such behavior shouldn't trigger timeouts to be shorter.
The only other thing I can think of is Lwt.bind, but that would be a severe performance hit.

Also, I think the libev man page overstates the performance impact of sampling time on linux. The VDSO makes such operations significantly faster. Especially the clock_gettime() used by libev should be in the nanosecond range as shown by e.g. https://stackoverflow.com/a/13096917
Of course the callout to C from OCaml makes it unsuitable for use during Lwt.bind, but updating the time base when using the timeout is probably doable.

Alternatively, the suggestion made by the libev man page (correcting for the time base discrepancy) is also an option, which might be more lightweight, since ev_now_update() seems to loop to perform a couple of updates and might also reschedule periodic timers internally.

**Comment by aantron** [comment]
I've been reading the source of libev and about the underlying functions involved. Here are some notes. I'm focusing on Linux, macOS, and Windows for now.

### Linux

- I haven't fully verified, but it looks like only Linux would have `EV_USE_MONOTONIC`, because that [guards](https://github.com/enki/libev/blob/93823e6ca699df195a6c7b8bfa6006ec40ee0003/ev.c#L1874-L1881) passing `CLOCK_MONOTONIC` to `clock_gettime`, and macOS [apparently does not support that constant](https://stackoverflow.com/questions/11680461/monotonic-clock-on-osx), although another constant [may give monotonic time](https://stackoverflow.com/a/11681069).
- So, [on Linux](https://github.com/enki/libev/blob/93823e6ca699df195a6c7b8bfa6006ec40ee0003/ev.c#L3468-L3515), there will be the (1) looping, querying clocks, and (2) potential rescheduling of "periodics," which are calendar-time timers. This operation (2) looks to take time at least linear in the number of periodics, but AFAICT independent of the number of ordinary timers. Lwt doesn't use periodics at all, so this should be no problem unless the user of Lwt is also using libev directly elsewhere in the same process. Does that happen?
- The four iterations checking clocks on Linux probably don't matter, especially if the time values are mapped directly into user space, as I assumed, as you suggest, and as the SO post you linked seems to confirm.

### macOS

- [This](https://github.com/enki/libev/blob/93823e6ca699df195a6c7b8bfa6006ec40ee0003/ev.c#L3518-L3531) is the code that will run on macOS. Periodics are again probably not a problem. There is no looping.
- `ev_time` will call either `clock_gettime(CLOCK_REALTIME)`, or `gettimeofday`. I didn't check if either one is all-userspace yet, though in my coding life to date, I always assumed that they were.
- [`timers_reschedule`](https://github.com/enki/libev/blob/93823e6ca699df195a6c7b8bfa6006ec40ee0003/ev.c#L3450-L3461) looks like it takes time at least linear in the number of timers. I haven't fully thought through the [condition](https://github.com/enki/libev/blob/93823e6ca699df195a6c7b8bfa6006ec40ee0003/ev.c#L3521) under which it will be called, but I think we definitely do not want this to happen every time someone creates a timeout – imagine a highly-concurrent Lwt server pairing a timeout with every I/O operation, and creating a new one of these updating all the existing ones. While I don't understand the expression in the `if` yet, the fact that [`REALTIME_CLOCK` in a Mach call is monotonic](https://stackoverflow.com/a/11681069) gives hope that this never gets triggered, together with the `expect_false`. So I'm optimistic here.

### Windows

- The [same `time_update` code](https://github.com/enki/libev/blob/93823e6ca699df195a6c7b8bfa6006ec40ee0003/ev.c#L3518-L3531) should run on Windows. However, the clock that is read is [read using `GetSystemTimeAsFileTime`](https://github.com/enki/libev/blob/93823e6ca699df195a6c7b8bfa6006ec40ee0003/ev_win32.c#L146-L159). I haven't looked into whether this function has high overhead or not, yet, nor whether it reports monotonic time.
- The other concerns from macOS apply, about running `timers_reschedule`.

**Comment by stijn-devriendt** [comment]
As per your concern of performance, we ultimately decided to take the safer route and apply the fix as suggested in the man page, by adjusting the timeout value. This only takes a single ev_time() call, which at least on Linux, is fast.

Mind that the code in the man page is wrong... I've requested some time to upstream our patch and hope to be able to do so this week.

**Comment by aantron** [comment]
It looks like performance of `ev_time` won't be a problem, including on Windows: https://stackoverflow.com/a/19052481. Thanks for the fix!
