### ISSUE TITLE
Calling exit in forked processes.

### ISSUE THREAD

**Issue by pveber** [ocsigen/lwt#472]
In a bigger program I needed a simple function to do multiprocessing. I wrote a (most certainly) naive implementation looking like that:
```ocaml
let compute f =
  match Unix.fork () with
  | 0 ->
    let ecode = try f () ; 0 with _ -> 1 in
    exit ecode
  | pid ->
    Lwt_unix.waitpid [] pid >>= fun (_, status) ->
    match status with
    | WEXITED code
    | WSIGNALED code
    | WSTOPPED code -> Lwt.return code
```
As it happens that the function `f` is expected to perform a side-effect, I thought I did not need a communication pipe, and could just use the exit code to say if everything went fine. It turns out that this does not work, because the children never actually stop. They seem to hang on the call to `exit` and I thought this might be related to `Lwt` (I'm guessing `Lwt` calls `at_exit` to put some clean-up callbacks). I tried variants using `Lwt_unix.fork` (although not necessary following the manual) and calling `Lwt_io.flush_all` before forking, but it didn't work (and led to very bizarre bugs, like files written with `Lwt_io.with_file` having their content duplicated several times, true story :o)...). 

I don't expect a precise answer here, since I'm not reporting a precise bug nor giving actual code to test (my program hangs in a very specific case, and I was not able at all to reduce to a simple example). So I just wanted to ask if there was something obviously wrong in the function above.

As a workaround, I reproduced the approach followed in [nproc](https://github.com/rizo/nproc/blob/master/nproc.ml), which is to communicate with children with a pipe, and kill the children when they are not needed anymore.

**Comment by aantron** [comment]
This reminds me of #48 and #114, which were fixed by 1254294524c3d2b7b4f370f6cb76f7728bcb75c4.

I don't see anything wrong with the above code, except that if `f` uses Lwt inside, you should use `Lwt_unix.fork`.

Some of the bugs seem pretty worrisome and serious, like the duplicated data.

I don't know if it can help, but there are examples of `fork`ing with Lwt in `lwt-parallel`:

-
 https://github.com/ivg/parallel/blob/fb44bc7dff556f246a7ab6007f77f975b5c61bd6/lib/parallel.ml#L167
- https://github.com/ivg/parallel/blob/fb44bc7dff556f246a7ab6007f77f975b5c61bd6/lib/parallel.ml#L178

Presumably, that is working correctly.

**Comment by aantron** [comment]
Closing this for now. Feel free to reopen if needed, and also I wonder what happened with this code :)

**Comment by pveber** [comment]
Sorry for not replying after that, I had to move on to something else and did not investigate further. Thanks a lot for your valuable feedback!

**Comment by aantron** [comment]
It's no problem, and understood :)
