### ISSUE TITLE
lwt_try with finally surprising evaluation order

### ISSUE THREAD

**Issue by ygrek** [ocsigen/lwt#54]
See discussion in https://sympa.inria.fr/sympa/arc/ocsigen/2014-04/msg00005.html

**Comment by aantron** [comment]
I agree that the order should be `with`, then `finally`. The PPX syntax already generates this order (it is different from the Camlp4 order).

Are you still using the Camlp4 extension and dealing with this problem? If not, then I propose, since nobody has complained yet about the different order between Camlp4 and PPX, to leave Camlp4 alone, and only document the order it generates. Hopefully, going forward, most users won't run into this issue, and the Camlp4 syntax will eventually be deprecated and removed.
