### ISSUE TITLE
Some historical archives of Lwt are missing from opam-repository

### ISSUE THREAD

**Issue by avsm** [ocsigen/lwt#589]
According to `opam admin cache`, these archives no longer exist from upstream ocsigen.org:

```
  - [lwt.2.3.2] http://ocsigen.org/download/lwt-2.3.2.tar.gz (curl: code 404 while downloading http://ocsigen.org/download/lwt-2.3.2.tar.gz)
  - [lwt.2.4.0] http://ocsigen.org/download/lwt-2.4.0.tar.gz (curl: code 404 while downloading http://ocsigen.org/download/lwt-2.4.0.tar.gz)
  - [lwt.2.4.1] http://ocsigen.org/download/lwt-2.4.1.tar.gz (curl: code 404 while downloading http://ocsigen.org/download/lwt-2.4.1.tar.gz)
  - [lwt.2.4.2] http://ocsigen.org/download/lwt-2.4.2.tar.gz (curl: code 404 while downloading http://ocsigen.org/download/lwt-2.4.2.tar.gz)
```

**Comment by aantron** [comment]
@balat, Is possible to recover the files that used to be on ocsigen.org? I can attach them as artifacts to the GitHub releases, and point the opam URLs there.

The reason is that the git tags don't seem to have the OASIS-generated boilerplate checked in. If we can get the original archives that were hosted on ocsigen.org, we can post known-working Lwt versions, instead of risking mistakes generating the release boilerplate again.

**Comment by balat** [comment]
Thanks! It should be fixed now. Sorry for the missing files.
We are still working on removing some dead links.

**Comment by aantron** [comment]
I've also uploaded those releases to GitHub, attaching them to the tags. If we have a problem with them again, we can use the files on GitHub as a backup.
