### ISSUE TITLE
Lwt.async not demanding `unit Lwt.t`

### ISSUE THREAD

**Issue by cfcs** [ocsigen/lwt#603]
I just bumped into a [pretty annoying bug](https://github.com/pqwy/notty/issues/22#issuecomment-407131608)

The result was ignored, which meant the callback `f` was never applied.
It seems to me that this could be a pretty common source of bugs, and that the benefit over just explicitly having `>|= fun _ -> ()` at the end if you *really* don't care about the result would be minimal.

I realize that this is not very surprising if you read the docstring (which likens it to `ignore`), but I've seen a fair share of code that uses `Lwt.async` as "please spawn a new Lwt promise and evaluate it," and I use it like that too.

EDIT: Forgot my main request: Would it be possible to change this from `(unit -> 'a Lwt.t) -> unit` to simply `(unit -> unit Lwt.t) -> unit` ?

Alternatively, if you do not want to change it, and it's just a debug function (as the docstring implies), maybe there could be a compile-time warning?

**Comment by aantron** [comment]
Changing it to `(unit -> unit Lwt.t) -> unit` does seem like the wisest thing to do here, in addition to maybe some doc clarifications. Factoring out the `ignore` seems smart, and people can explicitly do `>|= ignore` at the end, as you suggest.

I'll let other people comment if they would like. I'll have to look through the public code depending on `Lwt.async` to estimate how much damage breaking this would do.

**Comment by aantron** [comment]
Ok, the number of occurrences of `Lwt.async` is too large to look into each one separately. I sampled a few. Many occurrences are already being given a `unit -> unit Lwt.t` function, but some aren't, so the latter will break.


I think the most time-efficient way to find out what breaks will be to do the 5.0.0 release with `unit Lwt.t`, and let the opam CI build the reverse dependencies. We can notify the maintainers then.


The good news is that the breaking change is backwards-compatible, so some existing packages will need `lwt < "5.0.0"`, but their fixed releases will not need any constraint, and will be compatible with current and old Lwt.

**Comment by hannesm** [comment]
I fully appreciate this breaking change!  Thanks!

**Comment by cfcs** [comment]
@aantron Thanks for looking into this!
If you have decided to go ahead with this, we could also try to upstream some `>|= ignore` patches, referencing this future change.

**Comment by aantron** [comment]
Yep, I think we will do this.

I'm in favor of upstreaming patches, but it's labor-intensive to find out which libraries need them. Probably the easiest way is to run a script that will try to install packages depending on Lwt, and see which installs fail. I used to do this locally, but I think the cheapest way to do that now is by taking advantage of the revdeps build in opam's CI. So, I recommend simply doing this change, then releasing Lwt 5.0.0, and notifying maintainers after.

We could also create a fake "do not merge" Lwt PR to the opam repo, with the change applied, and see what is affected in the revdeps build.

**Comment by cfcs** [comment]
I think triggering a revdeps CI build sounds like a great idea; since the change should be "mostly backwards compatible" it could be a relatively small set of libraries that need to be changed, and it would be nice if could prevent breakage entirely. Would it be tricky to trigger such a build with *only* this change (ie not the whole `4.x -> 5.0` patchset)?

**Comment by aantron** [comment]
Ok, I did it right away :) https://github.com/ocaml/opam-repository/pull/12409

**Comment by aantron** [comment]
So far, the revdeps build has found breakage in:

[`tcpip`](https://ci.ocamllabs.io/log/saved/docker-run-c213f622168782a4accca538e8cb680c/252c79e984825b2d327f13e009580582a6cded40)
[`js_of_ocaml-lwt`](https://ci.ocamllabs.io/log/saved/docker-run-994f9b656fb2a27f8c0d8102e988759f/6e78df9f252615d8591fd98ac4e6d4caea0dd081)
[`devkit`](https://ci.ocamllabs.io/log/saved/docker-run-ee60068ffcc688d87ff9203e18cb5036/9fc056d45f44320ae8fc900cd57335d2eee6d149)
[`distributed-lwt`](https://ci.ocamllabs.io/log/saved/docker-run-b8c9c2140e5d8d9f97352ea072190cf3/4f599091ccbfb6a4fcc4ed0416cbb7aec935c7c7)
[`lwt_named_threads`](https://ci.ocamllabs.io/log/saved/docker-run-0281b09512b85a11bdccbb6b061c589c/06369cb6970b0e4be26aff4561d421a56139aaaa)
[`notty`](https://ci.ocamllabs.io/log/saved/docker-run-e2c99ee3662a4d1227166768718edb30/c02838c01eef76308cc5b1ead25e37e710d1c656)

Surprisingly few packages are affected. However, I'm not convinced that the CI is finding all the dependencies, so I will look into that.

**Comment by aantron** [comment]
Thanks, it would be welcome :)

We can notify the maintainers as well, like normal. I just haven't done this yet. Wanted to get the list of packages, and ping maintainers later.

**Comment by cfcs** [comment]
Fixed in `notty` as of https://github.com/pqwy/notty/commit/132358915fe18cc97cf5f06764c60eab2130bf03

**Comment by aantron** [comment]
Thanks!

**Comment by aantron** [comment]
This message is to notify of an upcoming breaking change in Lwt. Around November of this year (2019), Lwt 5.0.0 will be released, and the signature of [`Lwt.async`](https://github.com/ocsigen/lwt/blob/705a206ad64149be6cc93bb1447ce22fd14017ca/src/core/lwt.mli#L792) will change from

```ocaml
Lwt.async : (unit -> _ Lwt.t) -> unit
```

to

```ocaml
Lwt.async : (unit -> unit Lwt.t) -> unit
```

See this very issue, https://github.com/ocsigen/lwt/issues/603, for discussion.

A build of reverse dependencies of Lwt in opam shows at least the following packages will be affected:

- [`arp-mirage`](https://ci.ocaml.org/log/saved/docker-run-bd8d0bbc84ff9ac2765dd9b421414ca0/f4889910e53864b3220c46edd2e9f5fa5fffa511) @hannesm
- [`devkit`](https://ci.ocaml.org/log/saved/docker-run-1b668d25880b2089fe2339760090a1cb/44f83e70d85b896cadc844c1b3b1940f7837245a) @cyberhuman
- [`distributed-lwt`](https://ci.ocaml.org/log/saved/docker-run-746c1917eb68a90d43b939a0122ac469/d98bb26481eb2657a0a8deccef11d1b1dbfe8a3c) @essdotteedot
- [`js_of_ocaml-lwt`](https://ci.ocaml.org/log/saved/docker-run-08294ede8387592b3f95ca9a7f9938d7/8c61f66613392ca51dc6f994cf12954d06ed29e5) @avsm @hannesm @yomimono
- [`links`](https://ci.ocaml.org/log/saved/docker-run-29e5cf8eaf7e9b068eb1901bbf1ab9eb/8525ef5b6f7bb3fbe0a75118ae704e0ee7657e16) @dhil
- [`lwt_named_threads`](https://ci.ocaml.org/log/saved/docker-run-2da982cd3b04f06baa95c438c2bb9698/7c7de0344fb26936c038ae4ebc1bcd6ded30ce32) @gdsfh
- [`tcpip`](https://ci.ocaml.org/log/saved/docker-run-57b4d5557ecb854eb15b1b4b52b70abf/0c3fce9dd4cf9660ac53983852a5cbaf28b843b0) @hhugo

Each package name is linked to a log showing a compilation error due to this change. *The change has not been made yet; the errors were triggered by a dummy Lwt "release" made for this purpose only.*

If you are ccd in this message, please adapt your code so that it assumes `Lwt.async` has the second, future signature. This can be done at any time, including now :) No version constraints on Lwt will be necessary from this change, because the adapted code should be backwards- and forwards-compatible with all versions of Lwt.

When we release Lwt 5.0.0 (in three months), we will add the proper constraints to existing releases of these packages in opam, so you don't need to change their version constraints yourself, either.
