### ISSUE TITLE
about Lwt_bytes.mincore usage

### ISSUE THREAD

**Issue by cedlemo** [ocsigen/lwt#625]
I am not able to use correctly `Lwt_bytes.mincore`, here is what I have tried:

```ocaml
      let test_file = "bytes_io_data" in
      let fd = Unix.openfile test_file [O_RDONLY] 0 in
      let shared = false in
      let size = 6 in
      let buffer = Lwt_bytes.map_file ~fd ~shared ~size () in
      let states = Array.make 1 false in
      let () = Lwt_bytes.mincore buffer 0 states in
```
this code throws: 

```
'mincore' raised 'Invalid_argument("Lwt_bytes.mincore")'
```

I looked at the [C code but it does not help much](https://github.com/ocsigen/lwt/blob/master/src/unix/unix_c/unix_mincore.c): 

```c
#ifdef HAVE_BSD_MINCORE
#define MINCORE_VECTOR_TYPE char
#else
#define MINCORE_VECTOR_TYPE unsigned char
#endif

CAMLprim value lwt_unix_mincore(value val_buffer, value val_offset,
                                value val_length, value val_states)
{
    long len = Wosize_val(val_states);
    MINCORE_VECTOR_TYPE vec[len];
    mincore((char *)Caml_ba_data_val(val_buffer) + Long_val(val_offset),
            Long_val(val_length), vec);
    long i;
    for (i = 0; i < len; i++) Field(val_states, i) = Val_bool(vec[i] & 1);
    return Val_unit;
}
```

any hints?

**Comment by aantron** [comment]
The test is probably failing this check:

https://github.com/ocsigen/lwt/blob/ac8f7b15733bd9e3992764736d8860ca6c9fa379/src/unix/lwt_bytes.ml#L243

which *may* be too aggressive, because it checks there must be a number of *full* pages equal to the length of `states` after `offset` in the mapped buffer. This means the smallest possible buffer for which `Lwt_bytes.mincore` would usefully work has length 4096 (or 4M, depending on the page size).

To see if this is too restrictive, I suggest commenting out that check, and seeing if the underlying `mincore(2)` call still works, the test case asking about one page in a buffer of length 6. If it does work, we have caught Lwt's first bug with these tests :) In that case, we need to change the check to allow the last page queried to only partially overlap the buffer.

**Comment by cedlemo** [comment]
It works when I comment the last check, I prepare you a PR that modifies the check in `mincore`.
