### ISSUE TITLE
Bug in Lwt_react.with_finaliser under Flambda

### ISSUE THREAD

**Issue by stedolan** [ocsigen/lwt#626]
The implementation of Lwt_react.with_finaliser doesn't work under Flambda, since `ignore r` gets optimised away and allows the finaliser to run too early. Replacing `ignore r` with `ignore (Sys.opaque_identity r)` fixes this.

(This was reported to the OCaml bugtracker at https://caml.inria.fr/mantis/view.php?id=7861, see the discussion there for more details)

**Comment by aantron** [comment]
Thanks!

[`Sys.opaque_identity`](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Sys.html#VALopaque_identity) requires OCaml 4.03, but Lwt still supports OCaml 4.02. We may need to use cppo to get this fixed.

We probably need to:

1. Rename [`lwt_react.ml`](https://github.com/ocsigen/lwt/tree/master/src/react) to `lwt_react.cppo.ml`.
2. Modify the [Lwt_react `dune` file](https://github.com/ocsigen/lwt/blob/master/src/react/dune) to run cppo on `lwt_react.cppo.ml`, producing `lwt_react.ml` during the build. See [`test/unix/dune`](https://github.com/ocsigen/lwt/blob/ac8f7b15733bd9e3992764736d8860ca6c9fa379/test/unix/dune#L1-L4) for reference. These two steps should be done in one commit, so that tests continue to pass, and git can easily find the renamed file.
3. In a second commit, add conditional compilation so that on 4.02, we are still using `ignore` [as now](https://github.com/ocsigen/lwt/blob/ac8f7b15733bd9e3992764736d8860ca6c9fa379/src/react/lwt_react.ml#L23), but on 4.03 and later we start using `Sys.opaque_identity`.

Help:

- [Here](https://github.com/ocsigen/lwt/blob/ac8f7b15733bd9e3992764736d8860ca6c9fa379/test/unix/test_lwt_unix.cppo.ml#L38-L47) is an example of conditional compilation already being done in Lwt.
- [cppo usage](https://github.com/mjambon/cppo#conditionals).

The bug was reported in `Lwt_react.E.with_finaliser`, but it is likely that [`Lwt_react.S.with_finaliser`](https://github.com/ocsigen/lwt/blob/ac8f7b15733bd9e3992764736d8860ca6c9fa379/src/react/lwt_react.ml#L267) has the same problem. We should probably fix that function as well.

**Comment by aantron** [comment]
This was tentatively fixed in #629, thanks to @foocraft.

**Comment by aantron** [comment]
The linked commits also fix the bug in `Lwt_react.S.with_finaliser` and add test cases.
