### ISSUE TITLE
fork() crashes on macOS mojave

### ISSUE THREAD

**Issue by vincentdchan** [ocsigen/lwt#638]
I am working on macOS majave v10.14.1, after my program call fork(), the child process crashes with error:
```
+[__NSPlaceholderArray initialize] may have been in progress in another thread when fork() was called. 
```
I suppose it's related to some security issues occur in the new macOS versions. So I think lwt should support it.

**Comment by vincentdchan** [comment]
Sorry, I have tried my best to minimize the program but it's still large: [lwt-fork-example](https://github.com/vincentdchan/lwt-fork-example).

Build and run the program:
```sh
$ make
$ ./main.byte
```
when the server started, run the post script:
```sh
$ curl -X "POST" "http://localhost:8000/command/list?a=3" \
     -H 'Content-Type: application/x-www-form-urlencoded'
```

will trigger crashing, thank you.

**Comment by vincentdchan** [comment]
Error message:
```
objc[53503]: +[__NSPlaceholderArray initialize] may have been in progress in another thread when fork() was called.
objc[53503]: +[__NSPlaceholderArray initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

**Comment by aantron** [comment]
@vincentdchan You should be able to make it smaller by putting all the code in one file, then removing as many unnecessary types as you can, etc. At the least, for an example trying to be minimal, it is very helpful to have all the code in one place (unless it is many thousands of lines).

**Comment by vincentdchan** [comment]
@aantron Alright, I have put all the code into `main.ml`

**Comment by aantron** [comment]
Some more suggestions on minimizing it:

- Remove the dependency on `Command`, and hardcode the exact path your program will take to the bug. It looks like this only concerns a `-verbose` flag, but it is still a source of obfuscation and potential confounding factors.
- Remove loading of the config, and hardcode the values that cause the bug to the greatest extent possible. This is for the same reason as not having the code of a minimal example spread across multiple files.

These are only the first two things I saw, that you can remove to minimize the example. The second one in particular will remove quite some boilerplate from the code. There are likely more things to remove afterwards.

**Comment by vincentdchan** [comment]
@aantron No offence. I appreciate your work. But if you have looked through the code, why can't you debug? The program crashes at line 140, and you can see the call stacks, that's not so hard.

**Comment by aantron** [comment]
No problem.

The issues are that:

- The bug could be caused (1) by Lwt, (2) by another library you are using, (3) by a pathological interaction between Lwt and another library you are using, so both, and (4) by neither. So, it is helpful to reduce dependencies as much as possible. I would end up doing this work anyway as part of my debugging, but I will have to learn your code in order to delete parts of it. Since you already know your code, this is much easier for you to do than for me (i.e., I will be learning parts of your code simply to delete them, in addition to the parts I naturally have to learn in order to debug the "bug proper").
- There are several other, similar, bits of information we can learn by minimizing the code up front, distinguishing between various conditions and confounders.
- The line on which the code fails is useful information, so thank you, but while debugging, we may need to understand the actual execution trace, since `fork` seems to fail only under some conditions. This is another reason I will be deleting code. I will want to simplify this trace as much as possible.
- I don't have a Mac handy (mine "died" a few months ago), but I did download a Mojave ISO so I can run it in VirtualBox, when you opened this issue.
- It's possible, while minimizing the code on your end, which is, I believe, already the efficient thing to do for the first reason above, that we will stumble on the solution to the bug. Given that there are easy minimization steps you can efficiently take, which may on their own lead to the solution, it seems wasteful to have me set up a VM, to perform the same simplification process, which is inherently inefficient for me, to potentially reach the same conclusion.

Now, after minimizing the code further, there is a high likelihood that we will still be left with a mystery, where my familiarity with the internals of Lwt, and other such factors, will naturally make *my* labor the most efficient and fair way to continue debugging. At that point, I will happily set up the VM and get to proper work debugging this thing :)

**Comment by aantron** [comment]
Another thing I was going to suggest to remove next is the dependency on Core. Here's why this is easiest for you:

> Scanning through your code, I am not quickly sure if you are using Core in a "substantial" way, or it is mostly helpers like `List`. Part of the reason for this is the shadowing of standard library modules performed by Core. So, I might have to analyze your code for how it uses Core, but more likely I would just remove the `open`s and hope the program isn't using anything "non-trivial." If there is something non-trivial, I would be stuck reimplementing it, finding a replacement, or wondering if it's something that would be removed anyway in another minimization step, which again you could more easily perform than me.

Why remove Core?

A big library like Core is "difficult" to analyze. It may perform side effects at startup (`let () = foo` at the top level of a module) that affect the behavior of `fork` somehow, or the process after `fork`. We basically want to not link these side effects into the program, and see if there is still a problem.

If you are using something "non-trivial" from core, that complicates analysis of the execution trace, because we have to keep in mind the code of Core.

So removing Core both gives us a lot of information, because of the complexity of that library, and is also something easiest done up front, in minimization.

**Comment by vincentdchan** [comment]
@aantron Well. I am convinced by you just now. I have minimize the code to 141 lines, just checkout the repo. Thanks for you patience. Excellent project for excellent developer!

**Comment by aantron** [comment]
Thanks :) Could you give removing Core a shot? (I think we cross-posted). I think that would be one of the most informative things to do (whether the result is the bug is still there, or not).

**Comment by vincentdchan** [comment]
It's done. I have submitted a commit.

**Comment by aantron** [comment]
This looks like the last bit: https://github.com/vincentdchan/lwt-fork-example/blob/6e9fecfdf58cb6a64d55bc2960621d2fd388c45f/src/main.ml#L6

**Comment by vincentdchan** [comment]
Yeah. I have removed Core and preserved Core_Kernel. I suppose they are different.

**Comment by aantron** [comment]
Core_kernel is part of Core, it's the platform-independent part (IIRC) :) Core_kernel is itself a large package, so it would be helpful to remove it for the information that would yield.

**Comment by aantron** [comment]
Also, I recommend removing all the (now) unnecessary dependencies from the [_tags file](https://github.com/vincentdchan/lwt-fork-example/blob/6e9fecfdf58cb6a64d55bc2960621d2fd388c45f/_tags#L1), just in case something is pulling in `-linkall` somehow. I believe that should be `core_kernel`, and maybe `ppx_let` if you are not still using it after removing usage of Command. It looks like you've already been updating it, though.

**Comment by aantron** [comment]
Closing; please reopen if you've been able to narrow this further.
