### ISSUE TITLE
Lwt_unix dependenciess on Lwt_bytes

### ISSUE THREAD

**Issue by kydos** [ocsigen/lwt#641]
Lwt_bytes has a dependencies on Lwt_unix due to the function send, recv, read, etc. As a consequence Lwt_bytes cannot be used with js_of_ocaml which is a unfortunate as it would provide a nice way for libraries currently using it to transparently leveraging typed arrays in JS. 

Has removing the dependency from unix been considered in the next major release? We could potentially introduce a Lwt_bytes_io that provides the I/O operation mentioned above for the type Lwt_byte.t.

@kydos

**Comment by aantron** [comment]
@kydos `Lwt_bytes` without I/O is essentially [`Bigarray.Array1`](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Bigarray.Array1.html) from the standard library. Indeed, `Lwt_bytes.t` is [defined](https://ocsigen.org/lwt/3.2.1/api/Lwt_bytes#TYPEt) as

```ocaml
 (char, Bigarray.int8_unsigned_elt, Bigarray.c_layout) Bigarray.Array1.t
```

and the basic functions are defined mostly in terms of that module.

In light of that, is there a need for changing `Lwt_bytes`, or is this mainly a matter of porting a subset of `Bigarray.Array1` to JS?

**Comment by kydos** [comment]
@aantron for us it is simple to resolve this issue as we have a functor IOBuf that takes a backing-buffer module as parameter. Thus we can switch easily work around this. Yet, to me if looks a bit strange that a module that is called Lwt_bytes also provides I/O operations. Those seem to belong to Lwt_unix or perhaps to Lwt_bytes_unix or something like that.

**Comment by aantron** [comment]
It is indeed a bit strange, and most libraries separate some data type from I/O operations that work with it. However, in the case of `Lwt_bytes`, if one separates the I/O operations, the remaining "pure" data type is actually mostly an alias of `Bigarray.Array1`, so I suspect this is why `Lwt_bytes` is "combined" the way it is. I guess there wasn't that much value seen in having a separate pure `Lwt_bytes`, over just using `Array1`.

The dependency between `Lwt_unix` and `Lwt_bytes` is indeed backwards. You can see this also by the types in [`Lwt_unix.IO_vectors`](http://ocsigen.org/lwt/4.1.0/api/Lwt_unix.IO_vectors), which needs to depend on `Lwt_bytes`, but can't, because with the current `Lwt_bytes`, a dependency cycle would be introduced. So it uses a dummy type `_bigarray`, which has the same definition as `Lwt_bytes.t`.

However, at this point, the gain from rearranging this is probably not worth the pain of any backwards-compatibility breakage that may result. Of course, that estimate can change if we are really blocked from something by this, but right now (IMO) it's not a big enough problem to risk fixing :)

**Comment by kydos** [comment]
@aantron agreed. I'll close the issue. Thanks for the discussion!
