### ISSUE TITLE
Lwt_mvar extended functions

### ISSUE THREAD

**Issue by kydos** [ocsigen/lwt#643]
I would like to suggest the following addition to Lwt_mvar (where the type io should really be read as Lwt.t) :

   ```
    val guarded : 'a t -> ('a -> ('b io * 'a) io) -> 'b io
    (* [guarded] execute a function that changes the state and returns
        a result promise while ensuring the the mvar is acquired before 
        executing the function and released after even if exceptions
        are raised while running the function *)
    
    val guarded_and_then : 'a t -> ('a -> ('b io * 'a) io) -> ('a -> 'b io -> 'c io) -> 'c io
    (* [guarded_and_then m f g] runs  f as "guarded m f" but progagates the result and the new state
        to execute g. Notice that g cannot change the state thus is a read-only operation *)
     ```
A potential implementation is below:

   ```
    let guarded (m:'a t) (f : 'a -> ('b Lwt.t * 'a) Lwt.t) : 'b Lwt.t = 
      take m 
        >>= fun s -> Lwt.catch
          (fun () -> f s >>= fun (r, s') -> put m s' >>= fun () -> Lwt.return r)
          (fun e -> put m s >>= fun () -> Lwt.return (Lwt.fail e))
          >>= (fun r -> r)

    let guarded_and_then m f g = 
      take m 
      >>= fun s -> Lwt.catch 
        (fun () -> 
           f s >>= fun (r, s') -> put m s' >>= fun () -> 
            Lwt.catch 
              (fun () -> g s' r >>= fun r' -> Lwt.return r' )
              (fun e -> Lwt.fail e))
      (fun e -> put m s >>= fun () -> Lwt.fail e)```

**Comment by aantron** [comment]
My first impression is that these functions are complicated enough, that many users wouldn't know what to do with them. This suggests that they might not belong in the library. Can you provide some motivating examples?

Also, note that mvars aren't acquired and released.

I believe the implementation of `guarded` doesn't type-check, as I think the result type will be `'b io io`. The fix is easy, I think it will be just returning the final `Lwt.return`s in both branches of `catch`.

**Comment by aantron** [comment]
I suggest to keep these functions in a module of your project for now. This is because...

- They seem quite specialized, empirically suggested by them not having been requested before (AFAIK).
- It seems that they can be implemented without access to the internals of `Lwt_mvar` (unlike #642).

We will keep this issue in mind, and if someone else requests these helpers, or something similar, we can add them to `Lwt_mvar`.

**Comment by kydos** [comment]
Sounds good @aantron
