### ISSUE TITLE
Future of js-promises branch

### ISSUE THREAD

**Issue by osener** [ocsigen/lwt#647]
I'm using Lwt in a project which uses Native OCaml compiler & BuckleScript together with some code sharing, and having a pretty good experience with the `js-promises` branch. Are there any plans to move BuckleScript support forward?

**Comment by aantron** [comment]
@osener, the `js-promises` is based on JS promises in a naive way, the same way as `Js.Promise` from BuckleScript, and is susceptible to this problem: https://aantron.github.io/repromise/docs/DesignFAQ#why-are-js-promises-not-type-safe. I recommend using [Repromise](https://github.com/aantron/repromise) instead (which I think you are already trying), because it is meant to address that issue.

There are some plans for being able to run Lwt and Repromise in one process on the native side in the future, to be able to take advantage of all the native libraries based on Lwt.

One way is by basing Repromise on existing Lwt. A POC for this is [Repromise_lwt](https://github.com/aantron/repromise_lwt), [here](https://github.com/aantron/repromise_lwt/blob/315a149c591ba0ad6621da4f18ccf92df1b53ac5/test/test.re) is some sample code.

The other way is by binding to libuv, which is the C library that implements Node's I/O, and then having that binding drive both Lwt and Repromise. [Here](https://github.com/aantron/luv) is such a binding, and [sample code](https://github.com/aantron/luv/blob/82c49352da4401af5a6d1b520ddbb15bf73ad69e/example/interop_repromise_lwt/interop_repromise_lwt.re) showing Lwt and Repromise being used together.

The `js-promise` branch itself probably has no future for the above reasons. It was mostly useful for discovering the exact semantic differences between Lwt and JS promises by trying to substitute one with the other, so that the two could be integrated intelligently.

**Comment by aantron** [comment]
That should be possible, too. It would still be missing some of the other Lwt features that `js-promises` is missing, like cancellation, but most of these are "discouraged" anyway.

**Comment by aantron** [comment]
Note that some of the semantics of `js-promises` are different, both now, and if built (directly) over Repromise. For example, `js-promises` always defers callback calls to the next tick, while Lwt sometimes runs callbacks immediately.

**Comment by osener** [comment]
> Note that some of the semantics of js-promises are different,

Wouldn't expect to be otherwise, wrong word choice.

**Comment by osener** [comment]
I'll give a repromise-based Lwt a chance when I have the time!

**Comment by aantron** [comment]
Ok, great :)
