### ISSUE TITLE
Is resolving promise from another thread safe?

### ISSUE THREAD

**Issue by Lupus** [ocsigen/lwt#689]
I'm binding some C library via Ctypes, and it expects me to pass a callback that it will call from some background thread. Ctypes can help me register this thread to ocaml runtime and acquire runtime lock, so that I can pass ocaml function there and have it safely executed (at least I hope so, have not tried it yet).

Is it safe to resolve a promise from such callback, running in another (ocaml-registered) thread? Documentation on Lwt_preemptive states that calling most of Lwt functions inside detached computation is unsafe, hence this question.

I don't need any fancy logic inside the callback, just capturing some arguments passed by the C library, and waking up the event loop is all I need.

**Comment by aantron** [comment]
It's not safe to do that. The reason is that resolving a promise immediately updates Lwt data structures, and can immediately trigger callbacks attached to that promise, and this will all be done in the other thread.

This is problematic in two ways: Lwt assumes that all updates to its data structures are done in the main thread, and so is not internally thread-safe. However, even if it were, the user's callbacks attached to Lwt promises also assume that they always run in the main thread, which is a minor reasoning advantage for users of Lwt (and similar libraries). Causing them to run in another thread will violate this assumption.

So, in this case, it's necessary to pass a message back to the main thread, and resolve the Lwt promise there. There are many ways to do this. You may find some of the discussion in [#666 "Lwt_main.run hanging (threads and integration with external event loop)"](https://github.com/ocsigen/lwt/issues/666) helpful :)

I suggest to leave this issue open as a reminder to document this briefly by `Lwt.wakeup_later` and related functions.

**Comment by Lupus** [comment]
Cool, thanks for the info! Looks like [Lwt notifications](https://ocsigen.org/lwt/4.1.0/api/Lwt_unix#2_Notifications) are the recommended way of sending events to the event loop from other threads. I'll give it a go!

**Comment by Lupus** [comment]
For the reference: Lwt notifications work just fine for sending events from other thread. Along with ctypes thread registration and runtime lock features I'm able to pass ocaml callback to C library which invokes it on some random background thread of its own. That's awesome!

**Comment by aantron** [comment]
Great, glad you have it working :)
