### ISSUE TITLE
Missing argument "suffix" in open_temp_file and with_temp_file

### ISSUE THREAD

**Issue by vog** [ocsigen/lwt#724]
The functions `Lwt_io.with_temp_file` and `Lwt_io.open_temp_file` do not accept a `?suffix` argument, even though `Unix.open_temp_file` does support that parameter.

Rationale: I just came around an actual use case where this is needed to work around an issue with a certain tool that runs sub process and needs a temporary file with a certain file extension, as it doesn't accept any file name, and can't output directly to stdout, either.

By the way, are there any plans for `mkdtemp` support? (as seen in https://linux.die.net/man/3/mkdtemp or https://fdopen.github.io/uwt/Uwt_base.Fs_functions.html). Ideally, such a function would be available through a high level `with_temp_dir` function. However, there seems to be no such function in OCaml's standard library ...

**Comment by aantron** [comment]
@vog, would you be willing to open a PR for adding a `?suffix` argument to these functions? They are pure OCaml code. It should be pretty easy to add an argument and a bit of extra logic around here:

https://github.com/ocsigen/lwt/blob/584f34262020bc97c992506255ecb63106f76d67/src/unix/lwt_io.ml#L1343-L1347

and propagate it to `with_temp_file`.

Then, you can immediately test it, to see if it addresses your use case.

As for `mkdtemp`, there are no plans for it. `mkdtemp` itself should be really easy to implement. It's just string manipulation. In fact, it can arguably use the same code as used for generating temporary file names.

On top of that, we'd want to call `mkdir`. Detecting races should be pretty straightforward, because `mkdir` fails with `EEXIST` if the directory already exists. We just have to call the Lwt `mkdir`:

https://github.com/ocsigen/lwt/blob/584f34262020bc97c992506255ecb63106f76d67/src/unix/lwt_unix.cppo.mli#L656-L657

and finally, wrap all that in an `with_temp_dir` that calls `Lwt_unix.rmdir`. All this can be done in pure OCaml, because `mkdir` and `rmdir` are already bound. If you need this function, would you be interested in submitting a separate PR for it?

**Comment by aantron** [comment]
Should be addressed by the two linked commits.

**Comment by vog** [comment]
@aantron Thanks for implementing those handy features! I would have loved to provide those implementations myself, but didn't yet find enough time for that.

**Comment by aantron** [comment]
No problem :) As you probably already saw, they are now released as part of Lwt 4.4.0.

**Comment by Tim-ats-d** [comment]
Is it still relevant?
