### ISSUE TITLE
test fail in lwt_unix

### ISSUE THREAD

**Issue by olafhering** [ocsigen/lwt#729]
A bytecode_only ocaml-4.05 fails in `runcheck`:
````
[   81s] $ (cd _build/default/test/unix && ./main.exe)
[   81s] Testing library 'unix'...
[   81s] ..............SSS.....................................................................................................SS...FFFFF..................................................SS................
[   81s] Test 'openfile: O_CLOEXEC' in suite 'lwt_unix' produced 'false'
[   81s] Test 'openfile: O_CLOEXEC not given' in suite 'lwt_unix' produced 'false'
[   81s] Test 'openfile: O_KEEPEXEC' in suite 'lwt_unix' produced 'false'
[   81s] Test 'openfile: O_CLOEXEC, O_KEEPEXEC' in suite 'lwt_unix' produced 'false'
[   81s] Test 'openfile: O_KEEPEXEC, O_CLOEXEC' in suite 'lwt_unix' produced 'false'
[   81s] error: Bad exit status from /var/tmp/rpm-tmp.8N96N3 (%check)
[   81s] 
[   81s] 
[   81s] RPM build errors:
[   81s]     Bad exit status from /var/tmp/rpm-tmp.8N96N3 (%check)
````

**Comment by olafhering** [comment]
[devel:languages:ocaml:bytecode_only/ocaml-lwt](https://build.opensuse.org/package/show/devel:languages:ocaml:bytecode_only/ocaml-lwt)

**Comment by aantron** [comment]
Lwt doesn't install on 4.05.0+bytecode-only because its dependency seq assumes a native-code compiler is installed, so I will fix that first. Are you using a patched seq in your build? If so, where can I find the patch? If not, how is the bytecode-only variant configured for you?

**Comment by aantron** [comment]
https://github.com/c-cube/seq/pull/5

**Comment by olafhering** [comment]
There is nothing special in seq, it is used as is: [devel:languages:ocaml:bytecode_only/ocaml-seq](https://build.opensuse.org/package/show/devel:languages:ocaml:bytecode_only/ocaml-seq)

**Comment by olafhering** [comment]
> [c-cube/seq#5](https://github.com/c-cube/seq/pull/5)

This assumes `opam` is used. But `opam` is not required to use ocaml.

**Comment by aantron** [comment]
Yes, most of us use multiple package managers with OCaml, you may note the text allows for that :) I linked the issue for me to keep track of it, not because I expect it to affect your builds. I needed that patch to reproduce the problem here, which I'm now debugging. Other opam users will benefit from it.

**Comment by aantron** [comment]
I am concerned however, about why seq 0.1 is working in your environment. This suggests either a configuration of OCaml that built `ocamlopt` anyway, or a stray `ocamlopt` in your environment. It's also possible that you have a different or patched Ocamlbuild, or there may be some other explanation for why the `.cmxa` and `.cmxs` targets appear to be built successfully.

**Comment by olafhering** [comment]
Looking through my [ocaml.spec](https://build.opensuse.org/package/show/devel:languages:ocaml/ocaml), there is just a `make world`, instead of a `make world.opt`. I think this is all it takes, and `dune` can deal with the result.

**Comment by aantron** [comment]
Ok, the explanation for the difference with seq in opam is that a port to Dune was done in [this fork](https://github.com/dune-universe/seq/tree/duniverse-0.1) and not upstreamed to seq, and not released to opam. `build.opensuse.org` is using this fork. That's for anyone else using opam that hits this issue in the near future.

**Comment by olafhering** [comment]
Ah, yes. There are quite some repositories without dune support, and that project fixes many of them.

**Comment by aantron** [comment]
I guess the only relevant result of the seq business for openSUSE, is that seq is about to be released again at version 0.2 (I suggest to watch https://github.com/ocaml/opam-repository/pull/14998). The 0.1 released (or proposed?) for openSUSE right now is in fact not 0.1, it's a patched version that should have been 0.2, and the 0.1 name is misleading. None of this particularly matters, since the code is the same, but for the sake of tidiness, I weakly suggest to wait for the impending seq release, and start seq off at 0.2, and point the URL to the main repo :)

I've proceeded with the actual issue locally in the meantime :)

**Comment by aantron** [comment]
@olafhering, I'm also remembering you mentioning about a (false) dependency cycle: lwt -> bisect_ppx -> ounit. This would only happen because ounit is a monorepo that also includes another package, ounit-lwt (see the `.opam` files in the [root directory of ounit](https://github.com/gildor478/ounit)).

That makes me concerned: which command is openSUSE using to build ounit (and perhaps also other packages)? For example, doing `dune build` typically builds all packages in a monorepo, but doing `dune build -p ounit` will build only the package ounit

 The latter is the standard command to issue in the OCaml ecosystem, for non-development builds, because many repos function as monorepos for a main package, and some secondary helper packages.

In the same way, I see that the openSUSE Lwt package includes `react` as a dependency. But, unless you are intentionally packaging Lwt_react, it shouldn't be there.

You may be intentionally packaging ounit with all its helpers, and Lwt with all its helpers, but that will lead to occasional dependency cycles, as above, because it is not an accurate translation of the true OCaml package boundaries.

**Comment by aantron** [comment]
...and Bisect_ppx is not a dependency of Lwt releases at all. It's a dev dependency that we have to [manually patch out](https://github.com/ocsigen/lwt/commit/0784245552ac0de3fa7cc1f5abef4cc9a2729b90#diff-0fb63e77f8d1f5e6dc36f9ccf11cabadL5) until ocaml/dune#57 is fixed.

**Comment by aantron** [comment]
Even more, ounit is a [dev-only dependency](https://github.com/aantron/bisect_ppx/blob/a00c26d5cd6b3f5938c2860e4e75a878cc696f32/bisect_ppx.opam#L30) of Bisect_ppx!

If your build command is `dune build`, Dune will build all packages in the repo with a development profile, which often pulls in tests, and therefore dev dependencies.

If your command is `dune build -p package-name`, Dune will build only the given package, and the minimum needed, usually not including tests, and therefore not pulling in dev dependencies.

I'm not sure how to interpret the openSUSE package metadata, but you basically want all these deps only for testing. You shouldn't include them for releases.

**Comment by aantron** [comment]
Great, I'll just add a few more comments for whenever you're looking into it.

- These two sections of the Dune manual show the options for building release packages: [1](https://dune.readthedocs.io/en/stable/usage.html#restricting-the-set-of-packages) [2](https://dune.readthedocs.io/en/stable/usage.html#invocation-from-opam). Even though the second one says it's for opam, it's really for all package managers, the Dune docs just more or less assume opam as "the" package manager.

- If your metadata is careful about both dev packages and not building everything in a monorepo, you will have no dependency cycles (except for the few still lurking in the more obscure corners of the OCaml ecosystem). It will, of course, also greatly reduce the amount of OCaml packages you have to deal with in openSUSE.

- IIRC, you are packaging Lwt because it was seemingly needed for ounit. But, if you truly only need ounit and not ounit-lwt, then, when you no longer try to build ounit-lwt, you won't have to package Lwt at all :) I'll still fix the underlying problem in this issue, however (and any other issues you may find, now or later).

- Probably the safest way to check if a git repo can be used directly, is to download the opam archive for a release, and diff it against the corresponding git tag (they can differ due to package submission tools). You should also look at the commit under the git tag, as it might be on a leaf branch whose purpose is specifically to delete dev code right before release. If all these diffs are only to metadata (mainly the `.opam` file), then using git directly is safe. This will be the case for the vast majority of repos. For a few repos, like Lwt, there is a small adjustment between the git version and the release (the patch I linked earlier). In general, though, we are working to get rid of any need for such adjustments, so even more git versions will be usable directly as releases. You can find links to the release archives on opam.ocaml.org. For example, at the bottom of [this page](https://opam.ocaml.org/packages/lwt/lwt.4.3.1/), is the archive for Lwt 4.3.1. If you need programmatic access, probably the easiest way is to clone [opam-repository](https://github.com/ocaml/opam-repository).

- > It would be cool if the `dune runtest` could use system libraries, instead of the one that was just built

    Wouldn't you want `runtest` to run against the copy of the library that was just built, with all other libraries it depends on taken from the system installation? I think this is what a lot of the code that is written by package authors for `runtest` assumes, too. Since that seems to be your current scheme, and it matches what the OCaml ecosystem expects, I'd suggest to keep it :)
