### ISSUE TITLE
Lwt thread-local storage is deprecated?

### ISSUE THREAD

**Issue by Lupus** [ocsigen/lwt#730]
I've stumbled across Lwt thread-local storage API, and noticed that it seems to be in deprecated section. I couldn't find any rationale behind this in issues, but may be I have not tried hard enough.

The use case I have in mind for this is to pass request id from HTTP server handler down to whatever code is there automagically, so that logging for example could augment the log line with request id if it is present.

Alternate approach would be to pass some context explicitly across all function calls, which is a bit more noisy, but otherwise is more clear and is less magical.

So the question I have: is Lwt thread-local storage indeed deprecated, and if yes --- why?

**Comment by aantron** [comment]
It's deprecated because it's magical, misleading, and fragile.

1. Magical: to a reader, it is effectively some kind of non-syntactic global variables with unclear semantics.

2. Misleading: it's not thread-local storage. Lwt doesn't do anything with threading (except in `Lwt_preemptive`). Thinking of it as thread-local storage leads right into (3), which is why I renamed it to "Sequence-associated storage" at some point.

3. Fragile: it is propagated by only `bind` and related sequencing functions. This means that, in a complex program, you may have it working. But then, if you change how your promises are composed in one place, for example by inserting an `Lwt.choose` or converting in one place to an explicit `Lwt.wait` + `Lwt.wakeup_later`, it can break the propagation of this storage, with the bug appearing in a totally different part of the program. This can potentially happen even if a library that you depend on and call into changes.

I recommend to use an explicit context.

**Comment by Lupus** [comment]
Got it, thanks for explanation!
