### ISSUE TITLE
Deprecation of Lwt.keys

### ISSUE THREAD

**Issue by Aaylor** [ocsigen/lwt#759]
Hello,

We are currently writing a web server using Cohttp and Lwt, with a quite large
existing code base; and we plan to use `Lwt.keys` in order to provide specific
context for each request we will execute (mostly for logging and error tracking
purpose). But I feel a little bit worried that `Lwt.keys` features is documented
in a category named `deprecated`, even if the feature itself is not deprecated
yet.

Do you really plan to deprecate the feature in the near (or not that near)
future? 

I understand that features provided by `Lwt.keys` may be quite dangerous, and
that it can be replaced, as stated in the documentation, by a passing values
explicitly. But in our specific case, it is a time saver! :)

NOTE: Our plan is to use the generated request identifier, which is the key to
an associative map storing requests contexts.

I took a look on other threading libraries, and some of them also have the same
notion of `keys`: a key shared by all thread, but on which associated data are
thread specific. It seems that `Async` (I'm not familiar with it at all) also
provide this kind of feature. Why do you want to consider it as deprecated? Is
it mainly because it has not been implemented in a satisfying way? Or is it
just because data manipulation is not explicit?

I know that the documentation has part of the answer, but I'm very curious to
understand your POV on why it is discouraged! :p

Thanks for the great work on Lwt!
Aaylor

**Comment by aantron** [comment]
The feature *is* deprecated, but I chose not to add any intra-language annotations because

1. It will remain indefinitely.
1. There are many users, and no very easy upgrade path, so it's best not to issue warnings.

In other words, there is no obvious action for a user to take in response to a warning, nor does a user need to take any action.

The main reasons for deprecation are:

1. The feature is difficult to use and explain exactly. It works as one would expect in simple cases, but can be a bit surprising in other scenarios. So, the simple mental model can be quite misleading.
2. Refactoring can "silently" change a simple case to one where something unexpected happens (unexpected under the simple model).
3. It can be confusing to readers. For example, it complicates analysis of any Lwt code it is used in, by people not immediately familiar with how this feature works.

So, I would like to discourage people from using it.  However, it's not wrong to use it if you are sure you know it's right for you, and have considered it carefully. This seems to be true in your case. So, it seems that the deprecation has had its intended effect :) So, go ahead and use it, if it is what you need. There are no plans to break or remove the feature.

**Comment by Aaylor** [comment]
Thanks for your answer ! We will then keep using `Lwt.keys` in the simplest way (by using our associative map to store the contexts). :)

1&2.Wouldn't an alternative version of `keys` where the user does not choose the value to store by himself be safier and easier to understand ? It would let Lwt generate a key when applying a function similar to `Lwt.with_value`, and let the user responsible to copy/store its own data using the generated key.
3. Well I can't agree more :p 

 Since the question have been answered, should we close the issue ?
Thanks again for your time !

**Comment by aantron** [comment]
> It would let Lwt generate a key when applying a function similar to Lwt.with_value, and let the user responsible to copy/store its own data using the generated key.

I don't understand the difference between this scheme and what Lwt has now, but I suspect that even if it is clearer or safer, it might still not be clear or safe enough to recommend casually using.

> Since the question have been answered, should we close the issue ?

Yes, I will close the issue to keep the repo tidy, since the main question seems answered, but feel free to discuss any remaining loose ends :)
