### ISSUE TITLE
Best way to determine `final` item in a stream

### ISSUE THREAD

**Issue by kohlivarun5** [ocsigen/lwt#792]
In some of our workflows, we have a need to determine if an item is the final or last item in the `Lwt_stream`. This is mostly useful in cases such as we need to tell an RPC client that the response is final. 

While doing `Lwt_stream.map` or `Lwt_stream.iter_s/p`, it would be good to know if the element is final. Looking at the APIs, it seems difficult to determine that using `closed` or `is_empty`. 

Is there any recommendation on what is the best way for this ?

**Comment by undu** [comment]
If the producer has closed the stream there may be items still waiting to be processed and similarly, just because all the items in the stream have been processed doesn't mean more items cannot be produced in the future.

To determine that the last possible item in the stream has been received both checks need to happen: that the producer has closed the stream and that there are no more items waiting to be produced. Here's an example of two promises waking each other up, where one finishes execution and the other needs to detect when to stop depending on the state of the channel: https://gitlab.com/unduthegun/adventofcode2019/-/blob/master/11/space_police.ml#L30

**Comment by kohlivarun5** [comment]
I was also thinking of doing `is_empty && is_closed`. But the fact that their APIs are different (is_empty is promise based) made me think there might be gotchas. Is there a specific reason `is_empty` returns a promise?

**Comment by raphael-proust** [comment]
The documentation of `Lwt_stream` is not the clearest. In particular, it doesn't explain the relationship between resolution and option very well. So this is based on looking at the implementation.

`Lwt_stream.map` is essentially an assemblage of `get`, the mapping function, and `from`.

```
let map f s =
  from (fun () -> get s >|= function
  | Some x -> Some (f x)
  | None -> None)
```

You can do something similar but pass the information about termination of the stream to the caller. One way to do that (but you might have specific needs) is:

```
(* call a callback when the stream ends *)
let process item ending s =
  from (fun () -> get s >|= function
    | Some x -> Some (item x)
    | None -> ending (); None)
```

**Comment by raphael-proust** [comment]
@kohlivarun5 Does the comment above fits your use-case? Do you need additional help? (Feel free to close the issue if so.)

**Comment by kohlivarun5** [comment]
You solution only tells when a stream has ended, but doesn't tell when the last element is processed. 
`is_empty && is_closed` seems to work, so will use that and close this
