### ISSUE TITLE
Better throttle module?

### ISSUE THREAD

**Issue by rgrinberg** [ocsigen/lwt#817]
The current throttle module has some inconvenient things about it:

* It requires instantiating a functor.
* It has a per unit of time rate limiting rate rather than a fixed capacity for jobs. A fixed job capacity is often all one needs.
* It requires Lwt_unix

I'd like to propose a simple throttling module:

```ocaml
  type t

  (** [create n] creates a throttler that allows to run [n] jobs at once *)
  val create : int -> t

  (** How many jobs can run at the same time *)
  val size : t -> int

  (** Change the number of jobs that can run at once *)
  val resize : t -> int -> unit Lwt.t

  (** Execute a job, waiting if too many jobs are already running *)
  val run : t -> f:(unit -> 'a Lwt.t) -> 'a Lwt.t

  (** Return the number of jobs currently running *)
  val running : t -> int
```

This is a simpler api that requires no functors or timers. How does that sound?

**Comment by kohlivarun5** [comment]
We have had similar use cases of throttling a bunch of operations based on available resources.
In our experience, [Lwt_pool](https://github.com/ocsigen/lwt/blob/6b86402dc564cedf9428361b2397c7af0a781daf/src/core/lwt_pool.mli) and [Lwt_stream.itern_n](https://github.com/ocsigen/lwt/blob/master/src/core/lwt_stream.mli#L312) did what you are suggesting.

Your suggestion looks pretty similar to Lwt_pool actually, so that might help you.

**Comment by aantron** [comment]
@rgrinberg, does `Lwt_pool` do what you want, as aptly suggested by @kohlivarun5?

**Comment by rgrinberg** [comment]
Yes, that should work. One issue is that one cannot resize the pool without kicking out all the jobs. But that should be fixable.
