### ISSUE TITLE
Questions about vocabulary in `lwt.ml`

### ISSUE THREAD

**Issue by francoisthire** [ocsigen/lwt#818]
The internal documentation of `src/core/lwt.ml` mention the term `cell` in the documentation but does not give a clear meaning of what it means and is used only at one specific place in the file. Is it possible to have more details behind this notion?

**Comment by raphael-proust** [comment]
Hi,

The word cell is used both in the internal and external documentation of Lwt. In the former the word "cell" is used by itself but in the latter it is a part of the noun phrase (/groupe nominal/) "memory cell". I believe that the two uses are equivalent: the public interface having a more explicit phrasing.

I also think that, at that stage it is used in a purposefully hand-wavy way. It could say that a promise is a "container for" or a "pointer to" or "data-structure containing" or some other such roughly equivalence sentence. Ultimately, a promise is an abstraction over a value that is not necessarily available immediately.

On the more concrete side of things, and because you are asking specifically about the implementation file: A promise is `type ('a, 'u, 'c) t = { mutable state : ('a, 'u, 'c) state }` where `'a`, `'b`, and `'c` are used to enforce invariants internally and the record with a single field is the *cell*. (And `state` is a sum type that covers the different possible content of the cell.)

Hope this help, let me know if you have more questions.

**Comment by francoisthire** [comment]
I think your explanation is enough. Don't you think that It makes sense to add something in the internal documentation to make this notion explicit? 

Thanks for your explanation!

**Comment by aantron** [comment]
It can be changed to "mutable memory cell" or the like. I used the term by analogy with "reference cell," but I decided not to use the word "reference" to avoid falsely implying that a promise is a `ref`. Changing it to "container" loses that it is mutable. At least in my experience, "cell" is the common term for a mutable "piece" of memory. Perhaps it can be changed to "mutable container," but it still loses the precision that it contains (up to) one "piece" of data proper (ok, datum).

You will also find `cell` used in a similar way in `lwt_preemptive.ml` (this time not by me). There is a whole internal module `CELL` with type `CELL.t`, field `cell`, etc. It is actually fairly standard usage.

**Comment by aantron** [comment]
> standard usage

Here is the first non-Excel example from a DuckDuckGo search for "reference cell": https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/reference-cells.

I'm not an F# programmer, just giving the first example. I used and encountered the term routinely in PL courses, while programming in SML, etc.

**Comment by aantron** [comment]
Likewise https://en.wikipedia.org/wiki/Memory_cell_(computing). That article is focused only on hardware, but the term is used in PL as well, where the memory cells usually "contain" data more abstract than single bits.

**Comment by francoisthire** [comment]
I have tried to have a better understanding of `Lwt.ml` and I read the `Lwt.ml` file. I have more questions:

In
```ocaml
    let run_regular_callbacks fs =
```
the line

```ocaml
        | Regular_callback_list_explicitly_removable_callback
            {contents = Some f} ->
          f result;
```

is a bit surprising because it requires an external mechanism for cleaning this this callback. IIUC, this is achieved only by the function `clear_explicitly_removable_callback_cell`. Maybe there should be a comment? 

What is the invariant related to this constructor? Only `add_explicitily_removable_*` functions should use that constructor? This invariant is not guaranteed by the type system right? 

Is there a policy to know when functions should use such mechanism? There are plenty of comments but I am still not sure why the callback could not be removed implicitely.

In function `run_callback_or_defer_it` I see:

```ocaml
        run_in_resolution_loop (fun () ->
          f ())
```

I would have thought it was for value-restriction but I have no complain when I remove it.

I see to magic constant here:

```ocaml
  let default_maximum_callback_nesting_depth = 42

  (* See [clear_explicitly_removable_callback_cell] and [merge_callbacks]. *)
  let cleanup_throttle = 42
```

Is there any discussion out there behind the choice of these values? It seems to me that these values may have an impact on the performances of applications using `lwt`, and still there is no way to configure them. 

In function 
```ocaml
  let wakeup_general api_function_name r result =
```
it ends with
```ocaml
      let State_may_have_changed p = resolve ~allow_deferring:false p result in
      ignore p
```
I don't understand this `ignore p`. Why not ignoring the result of `resolve` directly`?

For the function `no_cancel` there is comment which says:

```
        (* In this callback, [p'] will either still itself be pending, or it
           will have become a proxy for a pending promise. The reasoning for
           this is as in [protected] and [may_now_be_proxy], but even simpler,
           because [p'] is not cancelable. *)
```

The documentation says 

```
  Note that [p'] can still be canceled if [p] is canceled. [Lwt.no_cancel]
    only prevents cancellation of [p] and [p'] through [p'].
```

**Comment by aantron** [comment]
> In
>
> ```ocaml
>     let run_regular_callbacks fs =
> ```
>
> the line
>
> ```ocaml
>         | Regular_callback_list_explicitly_removable_callback
>             {contents = Some f} ->
>           f result;
> ```
>
> is a bit surprising because it requires an external mechanism for cleaning this this callback. IIUC, this is achieved only by the function `clear_explicitly_removable_callback_cell`. Maybe there should be a comment?

Please state your expectations and why you believe they are broken. What you have written is two facts, the relation between which might itself be based on your misunderstanding, or might trigger a misunderstanding in me (!) :) What exactly should be commented here? Guessing, I can offer this...

At the time this function is called, the entire data structure containing this callback cell, and all other callback cells from the same promise, is no longer accessible through the promise, because the promise has already be resolved. The last reference to it is held by the iteration of `run_regular_callbacks`. So, soon after the callback is called, it will be eligible for collection by the GC. Futhermore, there is no way to add any new callbacks to this set of callbacks, or to trigger them a second time, because that can only have been done through the promise when it was pending.

There is already a comment related to this in the surrounding function `run_callbacks`, in which `run_regular_callbacks` in only an internal helper:

https://github.com/ocsigen/lwt/blob/20e8836bbbf22c27f45e5586728507c7b4ffc53b/src/core/lwt.ml#L1171-L1179

<br/>

---

> What is the invariant related to this constructor? Only `add_explicitily_removable_*` functions should use that constructor? This invariant is not guaranteed by the type system right?
>
> Is there a policy to know when functions should use such mechanism? There are plenty of comments but I am still not sure why the callback could not be removed implicitely.

Addressing the last sentence is the probably the best for understanding this. It's not that some callbacks cannot be removed implcitly &mdash; as you can see from the answer to the previous quote, *all* callbacks are removed implicitly once the promise is resolved. They are called and then they get GCd &mdash; the promise has lost the reference to them. This is also commented on here:

https://github.com/ocsigen/lwt/blob/20e8836bbbf22c27f45e5586728507c7b4ffc53b/src/core/lwt.ml#L523-L532

The issue is that some callbacks need to be removed explicitly *before* that, and those are exactly the callbacks for which this constructor is used. As per the comment on `clear_explicitly_removable_callback_cell`, which you already mentioned:

https://github.com/ocsigen/lwt/blob/20e8836bbbf22c27f45e5586728507c7b4ffc53b/src/core/lwt.ml#L875-L895

I'm not sure what invariant there would be here to guarantee here. Each function just adds whatever kind of callback it can get away with. Roughly speaking, sequential composition functions (`bind`) don't need to ever try to proactively remove the callbacks that they add, so they add an implicitly-removed callback because this saves space. As per the comment, it's an optimization (perhaps even a premature one; I didn't originally make it or ever measure it, but callbacks do get added a *lot* in Lwt).

Concurrent composition "racing" functions like `Lwt.choose` (and some others) need to proactively remove callbacks once they know which "path" the computation has taken, or callbacks which can never be called can accumulate without bound. So, they use `Regular_callback_list_explicitly_removable_callback` with the more elaborate payload and more levels of indirection in it.

<br/>

---

> In function `run_callback_or_defer_it` I see:
>
> ```ocaml
>         run_in_resolution_loop (fun () ->
>           f ())
> ```
>
> I would have thought it was for value-restriction but I have no complain when I remove it.

Good point :) I don't know why that is like that anymore. Probably just for extra consistency, and with the hope that the compiler can optimize away this kind of eta-expansion.

<br/>

---

> I see to magic constant here:
>
> ```ocaml
>   let default_maximum_callback_nesting_depth = 42
>
>   (* See [clear_explicitly_removable_callback_cell] and [merge_callbacks]. *)
>   let cleanup_throttle = 42
> ```
>
> Is there any discussion out there behind the choice of these values? It seems to me that these values may have an impact on the performances of applications using `lwt`, and still there is no way to configure them.

Not to my knowledge. There are no reports of any effect of these values on the performance of Lwt, and there has been no request to configure them. I only imagine that they were originally added because setting them to `1` (rather, hardcoding Lwt as if they were `1`) *was* causing a performance issue, and some larger number had to be chosen, so it ended up being `42` :) Probably after `4` or `8` or so the cost of the cleanup scan is well-amortized so as to be trivial, and for enough promises the scan doesn't occur at all, yet `42` is not so large that the scan is delayed to the point where a memory leak is occurring in practice anyway, because the scan is just not being done.

<br/>

---

> In function
>
> ```ocaml
>   let wakeup_general api_function_name r result =
> ```
>
> it ends with
>
> ```ocaml
>       let State_may_have_changed p = resolve ~allow_deferring:false p result in
>       ignore p
> ```
>
> I don't understand this `ignore p`. Why not ignoring the result of `resolve` directly`?

Unpacking the GADT variand `State_may_have_changed p` to shadow an earlier `p`, with different phantom type variables, is a form of poor man's linear typing internally in `lwt.ml`. It is unpacked in this particular case for consistency, self-documentation, and future-proofing, since someone else editing this code in the future might forget to unpack it and shadow `p` after the call to `resolve`. You can see this through the comments and usage you will find if you search for `State_may_have_changed`. The comment in particular *directly* addresses ignoring this reference.

https://github.com/ocsigen/lwt/blob/20e8836bbbf22c27f45e5586728507c7b4ffc53b/src/core/lwt.ml#L657-L669

<br/>

---

> For the function `no_cancel` there is comment which says:
>
> ```
>         (* In this callback, [p'] will either still itself be pending, or it
>            will have become a proxy for a pending promise. The reasoning for
>            this is as in [protected] and [may_now_be_proxy], but even simpler,
>            because [p'] is not cancelable. *)
> ```
>
> The documentation says
>
> ```
>   Note that [p'] can still be canceled if [p] is canceled. [Lwt.no_cancel]
>     only prevents cancellation of [p] and [p'] through [p'].
> ```

This is a perfect example of why I asked earlier for you to state your actual expectations and what seems to violate them. This block states two facts, which are not in contradiction to each other.

I can only guess that you are conflating a promise being rejected with `Lwt.Canceled` with a canceling a promise.

Rejecting a promise with `Lwt.Canceled` will trigger ordinary *forward* propagation of this rejection from `p` to `p'`.

Cancelation specifically refers to a *backward* **search** from a promise to "earlier" promises to then reject with `Lwt.Canceled`. Applying this search to the `p'` from this comment case does nothing, so `p'` is not cancelable. You can still reject or cancel `p`, then causing `Lwt.Canceled` to propagate to `p'` by the other, normal, forward rejection propagation path.

https://github.com/ocsigen/lwt/blob/20e8836bbbf22c27f45e5586728507c7b4ffc53b/src/core/lwt.ml#L213-L250

https://github.com/ocsigen/lwt/blob/20e8836bbbf22c27f45e5586728507c7b4ffc53b/src/core/lwt.ml#L1434-L1445

https://github.com/ocsigen/lwt/blob/20e8836bbbf22c27f45e5586728507c7b4ffc53b/src/core/lwt.mli#L1096-L1099

https://github.com/ocsigen/lwt/blob/20e8836bbbf22c27f45e5586728507c7b4ffc53b/src/core/lwt.mli#L1141-L1142

https://github.com/ocsigen/lwt/blob/20e8836bbbf22c27f45e5586728507c7b4ffc53b/src/core/lwt.mli#L1181-L1187

Some of the confusion is probably caused by calling any promise that is rejected with `Lwt.Canceled` *canceled*, even if it was not a cancelable promise (so, it was canceled because you directly rejected it with `Lwt.Canceled`, or because this state was propagated to it *forward* to it from another promise). Perhaps it's best to avoid that, to make it easier to make a clearer mental distinction.

**Comment by francoisthire** [comment]
Ok, my bad. I am trying to get familiar with `Lwt` and it seems that I am a bit clumsy while writing my questions.

> Please state your expectations and why you believe they are broken.

I am not saying it is broken, I am just having a hard time to understand this thing I think.

> The issue is that some callbacks need to be removed explicitly before that, and those are exactly the callbacks for which this constructor is used.

OK I got it. It seems obvious now. So may I rephrase by saying that it is a way to ensure that the callback manually attached to a promise will be called only once?

> I'm not sure what invariant there would be here to guarantee here.

Inside `Lwt.ml`, this constructor can be used anywhere right? Why don't we make this constructor private so that we can ensure that only some specific functions are allowed to use that constructor?

This makes me wondering why:

```ocaml
  type 'a may_now_be_proxy =
    | State_may_now_be_pending_proxy :
      ('a, _, pending) promise -> 'a may_now_be_proxy
    [@@ocaml.unboxed]
```

is not declared `private` (it could be apparently). The same goes for `state_changed` but there are two occurrences in the remaining part of the file. This way, we ensure that the constructor cannot be used outside a delimited scope (inside `lwt.ml` of course).

> Not to my knowledge. There are no reports of any effect of these values on the performance of Lwt, and there has been no request to configure them.

Would it be worth to add comments to precise this or it is already implicit?

> Some of the confusion is probably caused by calling any promise that is rejected with Lwt.Canceled canceled, even if it was not a cancelable promise (so, it was canceled because you directly rejected it with Lwt.Canceled, or because this state was propagated to it forward to it from another promise). Perhaps it's best to avoid that, to make it easier to make a clearer mental distinction.

I suspected something like that. This is quite hard to get though. Is a paragraph with an example (I don't think it exists already in the documentaiton or code) that explains this difference would help? What do you think?

**Comment by aantron** [comment]
> OK I got it. It seems obvious now. So may I rephrase by saying that it is a way to ensure that the callback manually attached to a promise will be called only once?

Almost. What ensures that callbacks are called only once is simply that they are only called once by `run_callbacks`, this is only place that they are called, and that they have already been removed from the promise by then by mutating the promise's state, losing the reference to them, so it can't be done again.

What this specific constructor allows is making sure that some callbacks are *never* called. To take `Lwt.choose [p; p']` again, once `p` resolves, we don't want the callback attached to `p'` to also be called later if/when `p'` also resolves. Furthermore, we want not only to disable it, but to fully remove it, to avoid a memory leak if `Lwt.choose [p'', p']` is called, and so on, in a loop.

Another thing you could say about this is `Lwt.choose ps` attaches a *set* of (in general) different (but similar) callbacks to each of the promises in `ps`. We want to make sure that only one of those callbacks will ever be called, so when the first one is called, it immediately removes all its "sibling" others.

`Regular_callback_list_explicitly_removable_callback` allows the above. It is better to think of `Regular_callback_list_explicitly_removable_callback` as the default, and that `Regular_callback_list_implicitly_removed_callback` disallows the above, as the price of performing an optimization on the representation.

> > I'm not sure what invariant there would be here to guarantee here.
>
> Inside `Lwt.ml`, this constructor can be used anywhere right? Why don't we make this constructor private so that we can ensure that only some specific functions are allowed to use that constructor?

> This makes me wondering why:
>
> ```ocaml
>   type 'a may_now_be_proxy =
>     | State_may_now_be_pending_proxy :
>       ('a, _, pending) promise -> 'a may_now_be_proxy
>     [@@ocaml.unboxed]
> ```
>
> is not declared `private` (it could be apparently). The same goes for `state_changed` but there are two occurrences in the remaining part of the file. This way, we ensure that the constructor cannot be used outside a delimited scope (inside `lwt.ml` of course).

I (or perhaps @raphael-proust :) ) will merge a PR that does this. I don't recall trying it, but if this can work, it seems like a good idea.

> Would it be worth to add comments to precise this or it is already implicit?

Yes, this could be mentioned in a comment or comments.

> I suspected something like that. This is quite hard to get though. Is a paragraph with an example (I don't think it exists already in the documentaiton or code) that explains this difference would help? What do you think?

Yes, a well-crafted example might help.

So far, `Lwt.cancel` is soft-deprecated, and my approach to this question has been to explain `Lwt.cancel` to some degree, but also to discourage its use, naturally also avoiding some of the questions. It's a pretty difficult function to understand for other reasons also, besides the misleading interaction between the meanings of "cancelable" and "canceled."
