### ISSUE TITLE
Documentation of `protected` and similar functions

### ISSUE THREAD

**Issue by francoisthire** [ocsigen/lwt#821]
The documentation of `protected` says:

```ocaml
(** [Lwt.protected p] creates a {{: #VALcancel} cancelable} promise [p'] with
    the same state as [p]. However, cancellation, the backwards search described
    in {!Lwt.cancel}, stops at [p'], and does not continue to [p]. *)
```
However, on the following snippet:

```ocaml
let p,r = Lwt.task () in
let p' = Lwt.protected p in
let p'' = p >>= fun () -> Lwt.return (Lwt.state p = Lwt.state p') in
wakeup r () (* Lwt.state p'' = Return false *)
```
We can observe a difference. Here is the `utop` program:

```ocaml
let p,r = Lwt.task ();;
let p' = Lwt.protected p;;
let p'' = Lwt.bind p (fun () -> Lwt.return (Lwt.state p = Lwt.state p'));;
Lwt.wakeup r ();;
Lwt.state p'';; (* Return false *)
Lwt.state p';; (* Return () *)
Lwt.state p;; (* Return () *)
```

I understand that this may be a corner case, but it reveals, IHMO, an internal behaviour of `Lwt` and therefore should be documented. I suspect that  the documentation of `Lwt.no_cancel` is also affected and maybe other sequential operators?

**Comment by aantron** [comment]
Good catch. More precisely, it's not that this reveals internal behavior of Lwt. It's just the documentation is an over-simplified description of what happens. What it should convey is that state changes in `p` propagate [eventually] to `p'`, rather than imply that the state of `p'` is always the same as of `p`.

`Lwt.state` itself could use some extra documentation. Synchronous state query is a dubious operation, exactly because it can give surprising results if applied to promises that are involved in "networks" of callbacks that are currently being called. By comparison, it is not supported on JS at all, and was not implemented in the experimental JS-promise branch of Lwt.

**Comment by raphael-proust** [comment]
> state changes in `p` propagate [eventually] to `p'`,

"propagates within one tick of the scheduler"? The notion of "tick" is not very explicit in the documentation but there is a mention to it in `pause`.

Maybe rather than stating this with a word that is not clearly defined in the documentation, we could use "eventually" and then give a counter example showing that `let f () = Lwt.pause () >>= fun () -> Lwt.return (Lwt.state p = Lwt.state p') ;;` is a function that returns a promises that always resolve to `true`.

It's a stronger guarantee than "eventually" but I think it holds.


> Synchronous state query is a dubious operation

Following the above suggestion, we could also warn in the documentation of `state` that it is dubious and that it is made less dubious when immediately following a `pause` (i.e., at the beginning of a set of callback calls).

**Comment by aantron** [comment]
@raphael-proust AFAICT the issue here isn't the ticks (and Lwt doesn't have such a notion, it only arises in `lwt.unix`, specifically `Lwt_engine`). It's the order in which callbacks are called (and therefore the various promises are resolved) &mdash; because the state of `p'` will be updated in the same "tick," just by a different callback. So I'd rather not introduce ticks or `Lwt.pause` into this documentation, as they are red herrings, and the "bound" they give is too wide.
