### ISSUE TITLE
Lwt_process#close return non-sensical signal numbers

### ISSUE THREAD

**Issue by kit-ty-kate** [ocsigen/lwt#878]
Using the following test case:
```
open Lwt.Infix

let p =
  Lwt_process.with_process_in ~stdin:`Close ("", [|"sleep"; "100"|]) begin fun proc ->
    proc#close >|= function
    | Unix.WEXITED n -> print_endline ("exited: "^string_of_int n)
    | Unix.WSIGNALED n -> print_endline ("signaled: "^string_of_int n)
    | Unix.WSTOPPED n -> print_endline ("stopped: "^string_of_int n)
  end

let () =
  Lwt_main.run p
```
Killing the `sleep` process with various signal numbers:
* SIGKILL (9) gives `-7`
* SIGPIPE (13) gives `-8`
* SIGBUS (10) gives `-22`
* ...

Lwt version: 5.4.1
Platform: tested on macOS and Linux

**Comment by code-ghalib** [comment]
@kit-ty-kate The `Unix` module documents that signals returned are the ones from `Sys` module. These signal numbers are converted to OS-independent values since `Sys` is part of `Stdlib`:

For example, for this code:
```ocaml
let _ = List.map print_int Stdlib.Sys.[sigkill;sigpipe;sigpipe] |> ignore
```
On my macOS, this is what gets printed:
```
-7-8-8
```

You might be able to modify any comparisons/matches you have on the signal numbers to be with the values defined in the `Sys` module.

**Comment by kit-ty-kate** [comment]
Ah I see, indeed, my bad. I've opened an issue upstream in https://github.com/ocaml/ocaml/pull/10600 to improve the documentation. Thanks.
