### ISSUE TITLE
Backtraces not propagated through `Lwt.catch`

### ISSUE THREAD

**Issue by emchristiansen** [ocsigen/lwt#921]
It appears backtraces aren't propagating through `Lwt.catch`.

For example, in the following code I get stack traces if I call `run` but not if I call `run_catch` (the same code but wrapped in an `Lwt.catch`):

    let bar () : unit Lwt.t =
      assert false ;
      Lwt.return_unit
    
    let foo () : unit Lwt.t = bar ()
    
    let run () : unit Lwt.t = foo ()
    
    let run_catch () : unit Lwt.t =
      Lwt.catch run (fun exn ->
          Format.printf
            "@{<error>@{<title>Error@}@}@.  @[<h 0>%a@]@."
            Format.pp_print_text
            (Printexc.to_string exn) ;
          Lwt.return_unit)
    
    let () =
      print_endline "Start" ;
      (* This version doesn't print a stack trace. *)
      Lwt_main.run (run_catch ())
      (* This version does print a stack trace. *)
      (* Lwt_main.run (run ()) *)

See also: https://www.reddit.com/r/ocaml/comments/s3fvfw/unable_to_get_stack_traces_when_using_lwtcatch/

**Comment by raphael-proust** [comment]
This is a known limitation of Lwt. And it is not one which will be fixed. However, there is a  known solution:

Use the ppx syntax extension. (Unfortunately the doc is down right now, but you can generate it locally from the `src/ppx/ppx_lwt.mli` interface file.) This syntax extension provides a more-native syntax (e.g., `let%lwt x = blah () in …` instead of `blah () >>= fun x -> …`). In addition, it adds, during the rewriting phase, some code which restore the stack traces.
